In [1]:
import petl as etl
import csv
from petl import appendcsv

https://www.kaggle.com/gregorut/videogamesales
(Here the subpart of data is used)

In [2]:
game_data = [['Rank', 'Name', 'Platform', 'Year', 'Genre', 'NA Sales'],
             [1, 'WiiSports', 'Wii', 2006, 'Sports' , 41.49],
             [2, 'Super Mario Bros', 'NES', 1985, 'Platform', 29.08],
             [3, 'Mario Kart Wii', 'Wii', 2008, 'Racing', 15.85],
             [4, 'Wii Sports Resort', 'Wii', 2009, 'Sports', 15.75],
             [5, 'Pokemon Red/Pokemon Blue', 'GB', 1996, 'RolePlaying', 11.27]]

In [3]:
with open('./datasets/game.csv', 'w', newline='') as gamefile:
    
    writer = csv.writer(gamefile)
    
    writer.writerows(game_data)

#### video_game_details is a table container which can be iterated over, extracting data from the underlying file on demand.

In [4]:
video_game_details = etl.fromcsv('./datasets/game.csv')

In [5]:
etl.look(video_game_details)

+------+----------------------------+----------+--------+---------------+----------+
| Rank | Name                       | Platform | Year   | Genre         | NA Sales |
+======+============================+==========+========+===============+==========+
| '1'  | 'WiiSports'                | 'Wii'    | '2006' | 'Sports'      | '41.49'  |
+------+----------------------------+----------+--------+---------------+----------+
| '2'  | 'Super Mario Bros'         | 'NES'    | '1985' | 'Platform'    | '29.08'  |
+------+----------------------------+----------+--------+---------------+----------+
| '3'  | 'Mario Kart Wii'           | 'Wii'    | '2008' | 'Racing'      | '15.85'  |
+------+----------------------------+----------+--------+---------------+----------+
| '4'  | 'Wii Sports Resort'        | 'Wii'    | '2009' | 'Sports'      | '15.75'  |
+------+----------------------------+----------+--------+---------------+----------+
| '5'  | 'Pokemon Red/Pokemon Blue' | 'GB'     | '1996' | 'RolePlaying' | '11.27'  |
+------+----------------------------+----------+--------+---------------+----------+

#### Load S&P 500 data

We have created two datasets
- one containing 2018 and 2019 OHLC + Volume data
- one containing 2020 data until September

The goal is to append them to a single file later on

https://finance.yahoo.com/quote/%5EGSPC/history?period1=1514764800&period2=1601337600&interval=1d&filter=history&frequency=1d

we are taking S&P 500 (^GSPC) 1,jan,2018 to 29,sept,2020 daily data

In [6]:
data = etl.io.csv.fromcsv('./datasets/GSPC.csv')

In [7]:
data

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2018-01-02' | '2683.729980' | '2695.889893' | '2682.360107' | '2695.810059' | '2695.810059' | '3367250000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-03' | '2697.850098' | '2714.370117' | '2697.770020' | '2713.060059' | '2713.060059' | '3538660000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-04' | '2719.310059' | '2729.290039' | '2719.070068' | '2723.989990' | '2723.989990' | '3695260000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-05' | '2731.330078' | '2743.449951' | '2727.919922' | '2743.149902' | '2743.149902' | '3236620000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-08' | '2742.669922' | '2748.510010' | '2737.600098' | '2747.709961' | '2747.709961' | '3242650000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
...

In [8]:
data.nrows()

503

In [9]:
data.columns()['Date']

['2018-01-02',
 '2018-01-03',
 '2018-01-04',
 '2018-01-05',
 '2018-01-08',
 '2018-01-09',
 '2018-01-10',
 '2018-01-11',
 '2018-01-12',
 '2018-01-16',
 '2018-01-17',
 '2018-01-18',
 '2018-01-19',
 '2018-01-22',
 '2018-01-23',
 '2018-01-24',
 '2018-01-25',
 '2018-01-26',
 '2018-01-29',
 '2018-01-30',
 '2018-01-31',
 '2018-02-01',
 '2018-02-02',
 '2018-02-05',
 '2018-02-06',
 '2018-02-07',
 '2018-02-08',
 '2018-02-09',
 '2018-02-12',
 '2018-02-13',
 '2018-02-14',
 '2018-02-15',
 '2018-02-16',
 '2018-02-20',
 '2018-02-21',
 '2018-02-22',
 '2018-02-23',
 '2018-02-26',
 '2018-02-27',
 '2018-02-28',
 '2018-03-01',
 '2018-03-02',
 '2018-03-05',
 '2018-03-06',
 '2018-03-07',
 '2018-03-08',
 '2018-03-09',
 '2018-03-12',
 '2018-03-13',
 '2018-03-14',
 '2018-03-15',
 '2018-03-16',
 '2018-03-19',
 '2018-03-20',
 '2018-03-21',
 '2018-03-22',
 '2018-03-23',
 '2018-03-26',
 '2018-03-27',
 '2018-03-28',
 '2018-03-29',
 '2018-04-02',
 '2018-04-03',
 '2018-04-04',
 '2018-04-05',
 '2018-04-06',
 '2018-04-09',
 '2018-04-10',
 '2018-04-11',
 '2018-04-12',
 '2018-04-13',
 '2018-04-16',
 '2018-04-17',
 '2018-04-18',
 '2018-04-19',
 '2018-04-20',
 '2018-04-23',
 '2018-04-24',
 '2018-04-25',
 '2018-04-26',
 '2018-04-27',
 '2018-04-30',
 '2018-05-01',
 '2018-05-02',
 '2018-05-03',
 '2018-05-04',
 '2018-05-07',
 '2018-05-08',
 '2018-05-09',
 '2018-05-10',
 '2018-05-11',
 '2018-05-14',
 '2018-05-15',
 '2018-05-16',
 '2018-05-17',
 '2018-05-18',
 '2018-05-21',
 '2018-05-22',
 '2018-05-23',
 '2018-05-24',
 '2018-05-25',
 '2018-05-29',
 '2018-05-30',
 '2018-05-31',
 '2018-06-01',
 '2018-06-04',
 '2018-06-05',
 '2018-06-06',
 '2018-06-07',
 '2018-06-08',
 '2018-06-11',
 '2018-06-12',
 '2018-06-13',
 '2018-06-14',
 '2018-06-15',
 '2018-06-18',
 '2018-06-19',
 '2018-06-20',
 '2018-06-21',
 '2018-06-22',
 '2018-06-25',
 '2018-06-26',
 '2018-06-27',
 '2018-06-28',
 '2018-06-29',
 '2018-07-02',
 '2018-07-03',
 '2018-07-05',
 '2018-07-06',
 '2018-07-09',
 '2018-07-10',
 '2018-07-11',
 '2018-07-12',
 '2018-07-13',
 '2018-07-16',
 '2018-07-17',
 '2018-07-18',
 '2018-07-19',
 '2018-07-20',
 '2018-07-23',
 '2018-07-24',
 '2018-07-25',
 '2018-07-26',
 '2018-07-27',
 '2018-07-30',
 '2018-07-31',
 '2018-08-01',
 '2018-08-02',
 '2018-08-03',
 '2018-08-06',
 '2018-08-07',
 '2018-08-08',
 '2018-08-09',
 '2018-08-10',
 '2018-08-13',
 '2018-08-14',
 '2018-08-15',
 '2018-08-16',
 '2018-08-17',
 '2018-08-20',
 '2018-08-21',
 '2018-08-22',
 '2018-08-23',
 '2018-08-24',
 '2018-08-27',
 '2018-08-28',
 '2018-08-29',
 '2018-08-30',
 '2018-08-31',
 '2018-09-04',
 '2018-09-05',
 '2018-09-06',
 '2018-09-07',
 '2018-09-10',
 '2018-09-11',
 '2018-09-12',
 '2018-09-13',
 '2018-09-14',
 '2018-09-17',
 '2018-09-18',
 '2018-09-19',
 '2018-09-20',
 '2018-09-21',
 '2018-09-24',
 '2018-09-25',
 '2018-09-26',
 '2018-09-27',
 '2018-09-28',
 '2018-10-01',
 '2018-10-02',
 '2018-10-03',
 '2018-10-04',
 '2018-10-05',
 '2018-10-08',
 '2018-10-09',
 '2018-10-10',
 '2018-10-11',
 '2018-10-12',
 '2018-10-15',
 '2018-10-16',
 '2018-10-17',
 '2018-10-18',
 '2018-10-19',
 '2018-10-22',
 '2018-10-23',
 '2018-10-24',
 '2018-10-25',
 '2018-10-26',
 '2018-10-29',
 '2018-10-30',
 '2018-10-31',
 '2018-11-01',
 '2018-11-02',
 '2018-11-05',
 '2018-11-06',
 '2018-11-07',
 '2018-11-08',
 '2018-11-09',
 '2018-11-12',
 '2018-11-13',
 '2018-11-14',
 '2018-11-15',
 '2018-11-16',
 '2018-11-19',
 '2018-11-20',
 '2018-11-21',
 '2018-11-23',
 '2018-11-26',
 '2018-11-27',
 '2018-11-28',
 '2018-11-29',
 '2018-11-30',
 '2018-12-03',
 '2018-12-04',
 '2018-12-06',
 '2018-12-07',
 '2018-12-10',
 '2018-12-11',
 '2018-12-12',
 '2018-12-13',
 '2018-12-14',
 '2018-12-17',
 '2018-12-18',
 '2018-12-19',
 '2018-12-20',
 '2018-12-21',
 '2018-12-24',
 '2018-12-26',
 '2018-12-27',
 '2018-12-28',
 '2018-12-31',
 '2019-01-02',
 '2019-01-03',
 '2019-01-04',
 '2019-01-07',
 '2019-01-08',
 '2019-01-09',
 '2019-01-10',
 '2019-01-11',
 '2019-01-14',
 '2019-01-15',
 '2019-01-16',
 '2019-01-17',
 '2019-01-18',
 '2019-01-22',
 '2019-01-23',
 '2019-01-24',
 '2019-01-25',
 '2019-01-28',
 '2019-01-29',
 '2019-01-30',
 '2019-01-31',
 '2019-02-01',
 '2019-02-04',
 '2019-02-05',
 '2019-02-06',
 '2019-02-07',
 '2019-02-08',
 '2019-02-11',
 '2019-02-12',
 '2019-02-13',
 '2019-02-14',
 '2019-02-15',
 '2019-02-19',
 '2019-02-20',
 '2019-02-21',
 '2019-02-22',
 '2019-02-25',
 '2019-02-26',
 '2019-02-27',
 '2019-02-28',
 '2019-03-01',
 '2019-03-04',
 '2019-03-05',
 '2019-03-06',
 '2019-03-07',
 '2019-03-08',
 '2019-03-11',
 '2019-03-12',
 '2019-03-13',
 '2019-03-14',
 '2019-03-15',
 '2019-03-18',
 '2019-03-19',
 '2019-03-20',
 '2019-03-21',
 '2019-03-22',
 '2019-03-25',
 '2019-03-26',
 '2019-03-27',
 '2019-03-28',
 '2019-03-29',
 '2019-04-01',
 '2019-04-02',
 '2019-04-03',
 '2019-04-04',
 '2019-04-05',
 '2019-04-08',
 '2019-04-09',
 '2019-04-10',
 '2019-04-11',
 '2019-04-12',
 '2019-04-15',
 '2019-04-16',
 '2019-04-17',
 '2019-04-18',
 '2019-04-22',
 '2019-04-23',
 '2019-04-24',
 '2019-04-25',
 '2019-04-26',
 '2019-04-29',
 '2019-04-30',
 '2019-05-01',
 '2019-05-02',
 '2019-05-03',
 '2019-05-06',
 '2019-05-07',
 '2019-05-08',
 '2019-05-09',
 '2019-05-10',
 '2019-05-13',
 '2019-05-14',
 '2019-05-15',
 '2019-05-16',
 '2019-05-17',
 '2019-05-20',
 '2019-05-21',
 '2019-05-22',
 '2019-05-23',
 '2019-05-24',
 '2019-05-28',
 '2019-05-29',
 '2019-05-30',
 '2019-05-31',
 '2019-06-03',
 '2019-06-04',
 '2019-06-05',
 '2019-06-06',
 '2019-06-07',
 '2019-06-10',
 '2019-06-11',
 '2019-06-12',
 '2019-06-13',
 '2019-06-14',
 '2019-06-17',
 '2019-06-18',
 '2019-06-19',
 '2019-06-20',
 '2019-06-21',
 '2019-06-24',
 '2019-06-25',
 '2019-06-26',
 '2019-06-27',
 '2019-06-28',
 '2019-07-01',
 '2019-07-02',
 '2019-07-03',
 '2019-07-05',
 '2019-07-08',
 '2019-07-09',
 '2019-07-10',
 '2019-07-11',
 '2019-07-12',
 '2019-07-15',
 '2019-07-16',
 '2019-07-17',
 '2019-07-18',
 '2019-07-19',
 '2019-07-22',
 '2019-07-23',
 '2019-07-24',
 '2019-07-25',
 '2019-07-26',
 '2019-07-29',
 '2019-07-30',
 '2019-07-31',
 '2019-08-01',
 '2019-08-02',
 '2019-08-05',
 '2019-08-06',
 '2019-08-07',
 '2019-08-08',
 '2019-08-09',
 '2019-08-12',
 '2019-08-13',
 '2019-08-14',
 '2019-08-15',
 '2019-08-16',
 '2019-08-19',
 '2019-08-20',
 '2019-08-21',
 '2019-08-22',
 '2019-08-23',
 '2019-08-26',
 '2019-08-27',
 '2019-08-28',
 '2019-08-29',
 '2019-08-30',
 '2019-09-03',
 '2019-09-04',
 '2019-09-05',
 '2019-09-06',
 '2019-09-09',
 '2019-09-10',
 '2019-09-11',
 '2019-09-12',
 '2019-09-13',
 '2019-09-16',
 '2019-09-17',
 '2019-09-18',
 '2019-09-19',
 '2019-09-20',
 '2019-09-23',
 '2019-09-24',
 '2019-09-25',
 '2019-09-26',
 '2019-09-27',
 '2019-09-30',
 '2019-10-01',
 '2019-10-02',
 '2019-10-03',
 '2019-10-04',
 '2019-10-07',
 '2019-10-08',
 '2019-10-09',
 '2019-10-10',
 '2019-10-11',
 '2019-10-14',
 '2019-10-15',
 '2019-10-16',
 '2019-10-17',
 '2019-10-18',
 '2019-10-21',
 '2019-10-22',
 '2019-10-23',
 '2019-10-24',
 '2019-10-25',
 '2019-10-28',
 '2019-10-29',
 '2019-10-30',
 '2019-10-31',
 '2019-11-01',
 '2019-11-04',
 '2019-11-05',
 '2019-11-06',
 '2019-11-07',
 '2019-11-08',
 '2019-11-11',
 '2019-11-12',
 '2019-11-13',
 '2019-11-14',
 '2019-11-15',
 '2019-11-18',
 '2019-11-19',
 '2019-11-20',
 '2019-11-21',
 '2019-11-22',
 '2019-11-25',
 '2019-11-26',
 '2019-11-27',
 '2019-11-29',
 '2019-12-02',
 '2019-12-03',
 '2019-12-04',
 '2019-12-05',
 '2019-12-06',
 '2019-12-09',
 '2019-12-10',
 '2019-12-11',
 '2019-12-12',
 '2019-12-13',
 '2019-12-16',
 '2019-12-17',
 '2019-12-18',
 '2019-12-19',
 '2019-12-20',
 '2019-12-23',
 '2019-12-24',
 '2019-12-26',
 '2019-12-27',
 '2019-12-30',
 '2019-12-31']

In [10]:
etl.header(data)

('Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume')

In [11]:
etl.look(data, style='simple', limit = 9)

============  =============  =============  =============  =============  =============  ============
Date          Open           High           Low            Close          Adj Close      Volume
============  =============  =============  =============  =============  =============  ============
'2018-01-02'  '2683.729980'  '2695.889893'  '2682.360107'  '2695.810059'  '2695.810059'  '3367250000'
'2018-01-03'  '2697.850098'  '2714.370117'  '2697.770020'  '2713.060059'  '2713.060059'  '3538660000'
'2018-01-04'  '2719.310059'  '2729.290039'  '2719.070068'  '2723.989990'  '2723.989990'  '3695260000'
'2018-01-05'  '2731.330078'  '2743.449951'  '2727.919922'  '2743.149902'  '2743.149902'  '3236620000'
'2018-01-08'  '2742.669922'  '2748.510010'  '2737.600098'  '2747.709961'  '2747.709961'  '3242650000'
'2018-01-09'  '2751.149902'  '2759.139893'  '2747.860107'  '2751.290039'  '2751.290039'  '3453480000'
'2018-01-10'  '2745.550049'  '2750.800049'  '2736.060059'  '2748.229980'  '2748.229980'  '3576350000'
'2018-01-11'  '2752.969971'  '2767.560059'  '2752.780029'  '2767.560059'  '2767.560059'  '3641320000'
'2018-01-12'  '2770.179932'  '2787.850098'  '2769.639893'  '2786.239990'  '2786.239990'  '3573970000'
============  =============  =============  =============  =============  =============  ============
...

In [12]:
etl.head(data)

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2018-01-02' | '2683.729980' | '2695.889893' | '2682.360107' | '2695.810059' | '2695.810059' | '3367250000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-03' | '2697.850098' | '2714.370117' | '2697.770020' | '2713.060059' | '2713.060059' | '3538660000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-04' | '2719.310059' | '2729.290039' | '2719.070068' | '2723.989990' | '2723.989990' | '3695260000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-05' | '2731.330078' | '2743.449951' | '2727.919922' | '2743.149902' | '2743.149902' | '3236620000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-08' | '2742.669922' | '2748.510010' | '2737.600098' | '2747.709961' | '2747.709961' | '3242650000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+

#### View n rows
We can set the n parameter in the call to petl.head(). In a Jupyter notebook, ellispsis are used to indicate that more rows are present

In [13]:
etl.head(data, n=10)

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2018-01-02' | '2683.729980' | '2695.889893' | '2682.360107' | '2695.810059' | '2695.810059' | '3367250000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-03' | '2697.850098' | '2714.370117' | '2697.770020' | '2713.060059' | '2713.060059' | '3538660000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-04' | '2719.310059' | '2729.290039' | '2719.070068' | '2723.989990' | '2723.989990' | '3695260000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-05' | '2731.330078' | '2743.449951' | '2727.919922' | '2743.149902' | '2743.149902' | '3236620000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2018-01-08' | '2742.669922' | '2748.510010' | '2737.600098' | '2747.709961' | '2747.709961' | '3242650000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
...

In [14]:
data.display()

Date,Open,High,Low,Close,Adj Close,Volume
2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3367250000
2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3538660000
2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3695260000
2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3236620000
2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3242650000

In [15]:
data.display(limit=10)

Date,Open,High,Low,Close,Adj Close,Volume
2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3367250000
2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3538660000
2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3695260000
2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3236620000
2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3242650000
2018-01-09,2751.149902,2759.139893,2747.860107,2751.290039,2751.290039,3453480000
2018-01-10,2745.550049,2750.800049,2736.060059,2748.229980,2748.229980,3576350000
2018-01-11,2752.969971,2767.560059,2752.780029,2767.560059,2767.560059,3641320000
2018-01-12,2770.179932,2787.850098,2769.639893,2786.239990,2786.239990,3573970000
2018-01-16,2798.959961,2807.540039,2768.639893,2776.419922,2776.419922,4325970000

In [16]:
data.displayall()

Date,Open,High,Low,Close,Adj Close,Volume
2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3367250000
2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3538660000
2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3695260000
2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3236620000
2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3242650000
2018-01-09,2751.149902,2759.139893,2747.860107,2751.290039,2751.290039,3453480000
2018-01-10,2745.550049,2750.800049,2736.060059,2748.229980,2748.229980,3576350000
2018-01-11,2752.969971,2767.560059,2752.780029,2767.560059,2767.560059,3641320000
2018-01-12,2770.179932,2787.850098,2769.639893,2786.239990,2786.239990,3573970000
2018-01-16,2798.959961,2807.540039,2768.639893,2776.419922,2776.419922,4325970000
2018-01-17,2784.989990,2807.040039,2778.379883,2802.560059,2802.560059,3778050000
2018-01-18,2802.399902,2805.830078,2792.560059,2798.030029,2798.030029,3681470000
2018-01-19,2802.600098,2810.330078,2798.080078,2810.300049,2810.300049,3639430000
2018-01-22,2809.159912,2833.030029,2808.120117,2832.969971,2832.969971,3471780000
2018-01-23,2835.050049,2842.239990,2830.590088,2839.129883,2839.129883,3519650000
2018-01-24,2845.419922,2852.969971,2824.810059,2837.540039,2837.540039,4014070000
2018-01-25,2846.239990,2848.560059,2830.939941,2839.250000,2839.250000,3835150000
2018-01-26,2847.479980,2872.870117,2846.179932,2872.870117,2872.870117,3443230000
2018-01-29,2867.229980,2870.620117,2851.479980,2853.530029,2853.530029,3573830000
2018-01-30,2832.739990,2837.750000,2818.270020,2822.429932,2822.429932,3990650000
2018-01-31,2832.409912,2839.260010,2813.040039,2823.810059,2823.810059,4261280000
2018-02-01,2816.449951,2835.959961,2812.699951,2821.979980,2821.979980,3938450000
2018-02-02,2808.919922,2808.919922,2759.969971,2762.129883,2762.129883,4301130000
2018-02-05,2741.060059,2763.389893,2638.169922,2648.939941,2648.939941,5283460000
2018-02-06,2614.780029,2701.040039,2593.070068,2695.139893,2695.139893,5891660000
2018-02-07,2690.949951,2727.669922,2681.330078,2681.659912,2681.659912,4626570000
2018-02-08,2685.010010,2685.270020,2580.560059,2581.000000,2581.000000,5305440000
2018-02-09,2601.780029,2638.669922,2532.689941,2619.550049,2619.550049,5680070000
2018-02-12,2636.750000,2672.610107,2622.449951,2656.000000,2656.000000,4055790000
2018-02-13,2646.270020,2668.840088,2637.080078,2662.939941,2662.939941,3472870000
2018-02-14,2651.209961,2702.100098,2648.870117,2698.629883,2698.629883,4003740000
2018-02-15,2713.459961,2731.510010,2689.820068,2731.199951,2731.199951,3684910000
2018-02-16,2727.139893,2754.419922,2725.110107,2732.219971,2732.219971,3637460000
2018-02-20,2722.989990,2737.600098,2706.760010,2716.260010,2716.260010,3627610000
2018-02-21,2720.530029,2747.750000,2701.290039,2701.330078,2701.330078,3779400000
2018-02-22,2710.419922,2731.260010,2697.770020,2703.959961,2703.959961,3701270000
2018-02-23,2715.800049,2747.760010,2713.739990,2747.300049,2747.300049,3189190000
2018-02-26,2757.370117,2780.639893,2753.780029,2779.600098,2779.600098,3424650000
2018-02-27,2780.449951,2789.149902,2744.219971,2744.280029,2744.280029,3745080000
2018-02-28,2753.780029,2761.520020,2713.540039,2713.830078,2713.830078,4230660000
2018-03-01,2715.219971,2730.889893,2659.649902,2677.669922,2677.669922,4503970000
2018-03-02,2658.889893,2696.250000,2647.320068,2691.250000,2691.250000,3882450000
2018-03-05,2681.060059,2728.090088,2675.750000,2720.939941,2720.939941,3710810000
2018-03-06,2730.179932,2732.080078,2711.260010,2728.120117,2728.120117,3370690000
2018-03-07,2710.179932,2730.600098,2701.739990,2726.800049,2726.800049,3393270000
2018-03-08,2732.750000,2740.449951,2722.649902,2738.969971,2738.969971,3212320000
2018-03-09,2752.909912,2786.570068,2751.540039,2786.570068,2786.570068,3364100000
2018-03-12,2790.540039,2796.979980,2779.260010,2783.020020,2783.020020,3185020000
2018-03-13,2792.310059,2801.899902,2758.679932,2765.310059,2765.310059,3301650000
2018-03-14,2774.060059,2777.110107,2744.379883,2749.479980,2749.479980,3391360000
2018-03-15,2754.270020,2763.030029,2741.469971,2747.330078,2747.330078,3500330000
2018-03-16,2750.570068,2761.850098,2749.969971,2752.010010,2752.010010,5372340000
2018-03-19,2741.379883,2741.379883,2694.590088,2712.919922,2712.919922,3302130000
2018-03-20,2715.050049,2724.219971,2710.050049,2716.939941,2716.939941,3261030000
2018-03-21,2714.989990,2739.139893,2709.790039,2711.929932,2711.929932,3415510000
2018-03-22,2691.360107,2695.679932,2641.590088,2643.689941,2643.689941,3739800000
2018-03-23,2646.709961,2657.669922,2585.889893,2588.260010,2588.260010,3815080000
2018-03-26,2619.350098,2661.360107,2601.810059,2658.550049,2658.550049,3511100000
2018-03-27,2667.570068,2674.780029,2596.120117,2612.620117,2612.620117,3706350000
2018-03-28,2611.300049,2632.649902,2593.060059,2605.000000,2605.000000,3864500000
2018-03-29,2614.409912,2659.070068,2609.719971,2640.870117,2640.870117,3565990000
2018-04-02,2633.449951,2638.300049,2553.800049,2581.879883,2581.879883,3598520000
2018-04-03,2592.169922,2619.139893,2575.489990,2614.449951,2614.449951,3392810000
2018-04-04,2584.040039,2649.860107,2573.610107,2644.689941,2644.689941,3350340000
2018-04-05,2657.360107,2672.080078,2649.580078,2662.840088,2662.840088,3178970000
2018-04-06,2645.820068,2656.879883,2586.270020,2604.469971,2604.469971,3299700000
2018-04-09,2617.179932,2653.550049,2610.790039,2613.159912,2613.159912,3062960000
2018-04-10,2638.409912,2665.449951,2635.780029,2656.870117,2656.870117,3543930000
2018-04-11,2643.889893,2661.429932,2639.250000,2642.189941,2642.189941,3020760000
2018-04-12,2653.830078,2674.719971,2653.830078,2663.989990,2663.989990,3021320000
2018-04-13,2676.899902,2680.260010,2645.050049,2656.300049,2656.300049,2960910000
2018-04-16,2670.100098,2686.489990,2665.159912,2677.840088,2677.840088,3019700000
2018-04-17,2692.739990,2713.340088,2692.050049,2706.389893,2706.389893,3234360000
2018-04-18,2710.110107,2717.489990,2703.629883,2708.639893,2708.639893,3383410000
2018-04-19,2701.159912,2702.840088,2681.899902,2693.129883,2693.129883,3349370000
2018-04-20,2692.560059,2693.939941,2660.610107,2670.139893,2670.139893,3388590000
2018-04-23,2675.399902,2682.860107,2657.989990,2670.290039,2670.290039,3017480000
2018-04-24,2680.800049,2683.550049,2617.320068,2634.560059,2634.560059,3706740000
2018-04-25,2634.919922,2645.300049,2612.669922,2639.399902,2639.399902,3499440000
2018-04-26,2651.649902,2676.479980,2647.159912,2666.939941,2666.939941,3665720000
2018-04-27,2675.469971,2677.350098,2659.010010,2669.909912,2669.909912,3219030000
2018-04-30,2682.510010,2682.870117,2648.040039,2648.050049,2648.050049,3734530000
2018-05-01,2642.959961,2655.270020,2625.409912,2654.800049,2654.800049,3559850000
2018-05-02,2654.239990,2660.870117,2631.699951,2635.669922,2635.669922,4010770000
2018-05-03,2628.080078,2637.139893,2594.620117,2629.729980,2629.729980,3851470000
2018-05-04,2621.449951,2670.929932,2615.320068,2663.419922,2663.419922,3327220000
2018-05-07,2680.340088,2683.350098,2664.699951,2672.629883,2672.629883,3237960000
2018-05-08,2670.260010,2676.340088,2655.199951,2671.919922,2671.919922,3717570000
2018-05-09,2678.120117,2701.270020,2674.139893,2697.790039,2697.790039,3909500000
2018-05-10,2705.020020,2726.110107,2704.540039,2723.070068,2723.070068,3333050000
2018-05-11,2722.699951,2732.860107,2717.449951,2727.719971,2727.719971,2862700000
2018-05-14,2738.469971,2742.100098,2725.469971,2730.129883,2730.129883,2972660000
2018-05-15,2718.590088,2718.590088,2701.909912,2711.449951,2711.449951,3290680000
2018-05-16,2712.620117,2727.760010,2712.169922,2722.459961,2722.459961,3202670000
2018-05-17,2719.709961,2731.959961,2711.360107,2720.129883,2720.129883,3475400000
2018-05-18,2717.350098,2719.500000,2709.179932,2712.969971,2712.969971,3368690000
2018-05-21,2735.389893,2739.189941,2725.699951,2733.010010,2733.010010,3019890000
2018-05-22,2738.340088,2742.239990,2721.879883,2724.439941,2724.439941,3366310000
2018-05-23,2713.979980,2733.330078,2709.540039,2733.290039,2733.290039,3326290000
2018-05-24,2730.939941,2731.969971,2707.379883,2727.760010,2727.760010,3256030000
2018-05-25,2723.600098,2727.360107,2714.989990,2721.330078,2721.330078,2995260000
2018-05-29,2705.110107,2710.669922,2676.810059,2689.860107,2689.860107,3736890000
2018-05-30,2702.429932,2729.340088,2702.429932,2724.010010,2724.010010,3561050000
2018-05-31,2720.979980,2722.500000,2700.679932,2705.270020,2705.270020,4235370000
2018-06-01,2718.699951,2736.929932,2718.699951,2734.620117,2734.620117,3684130000
2018-06-04,2741.669922,2749.159912,2740.540039,2746.870117,2746.870117,3376510000
2018-06-05,2748.459961,2752.610107,2739.510010,2748.800049,2748.800049,3517790000
2018-06-06,2753.250000,2772.389893,2748.459961,2772.350098,2772.350098,3651640000
2018-06-07,2774.840088,2779.899902,2760.159912,2770.370117,2770.370117,3711330000
2018-06-08,2765.840088,2779.389893,2763.590088,2779.030029,2779.030029,3123210000
2018-06-11,2780.179932,2790.209961,2780.169922,2782.000000,2782.000000,3232330000
2018-06-12,2785.600098,2789.800049,2778.780029,2786.850098,2786.850098,3401010000
2018-06-13,2787.939941,2791.469971,2774.649902,2775.629883,2775.629883,3779230000
2018-06-14,2783.209961,2789.060059,2776.520020,2782.489990,2782.489990,3526890000
2018-06-15,2777.780029,2782.810059,2761.729980,2779.659912,2779.659912,5428790000
2018-06-18,2765.790039,2774.989990,2757.120117,2773.750000,2773.750000,3287150000
2018-06-19,2752.010010,2765.050049,2743.189941,2762.590088,2762.590088,3661470000
2018-06-20,2769.729980,2774.860107,2763.909912,2767.320068,2767.320068,3327600000
2018-06-21,2769.280029,2769.280029,2744.389893,2749.760010,2749.760010,3300060000
2018-06-22,2760.790039,2764.169922,2752.679932,2754.879883,2754.879883,5450550000
2018-06-25,2742.939941,2742.939941,2698.669922,2717.070068,2717.070068,3655080000
2018-06-26,2722.120117,2732.909912,2715.600098,2723.060059,2723.060059,3555090000
2018-06-27,2728.449951,2746.090088,2699.379883,2699.629883,2699.629883,3776090000
2018-06-28,2698.689941,2724.340088,2691.989990,2716.310059,2716.310059,3428140000
2018-06-29,2727.129883,2743.260010,2718.030029,2718.370117,2718.370117,3565620000
2018-07-02,2704.949951,2727.260010,2698.949951,2726.709961,2726.709961,3073650000
2018-07-03,2733.270020,2736.580078,2711.159912,2713.219971,2713.219971,1911470000
2018-07-05,2724.189941,2737.830078,2716.020020,2736.610107,2736.610107,2953420000
2018-07-06,2737.679932,2764.409912,2733.520020,2759.820068,2759.820068,2554780000
2018-07-09,2775.620117,2784.649902,2770.729980,2784.169922,2784.169922,3050040000
2018-07-10,2788.560059,2795.580078,2786.239990,2793.840088,2793.840088,3063850000
2018-07-11,2779.820068,2785.909912,2770.770020,2774.020020,2774.020020,2964740000
2018-07-12,2783.139893,2799.219971,2781.530029,2798.290039,2798.290039,2821690000
2018-07-13,2796.929932,2804.530029,2791.689941,2801.310059,2801.310059,2614000000
2018-07-16,2797.360107,2801.189941,2793.389893,2798.429932,2798.429932,2812230000
2018-07-17,2789.340088,2814.189941,2789.239990,2809.550049,2809.550049,3050730000
2018-07-18,2811.350098,2816.760010,2805.889893,2815.620117,2815.620117,3089780000
2018-07-19,2809.370117,2812.050049,2799.770020,2804.489990,2804.489990,3266700000
2018-07-20,2804.550049,2809.699951,2800.010010,2801.830078,2801.830078,3230210000
2018-07-23,2799.169922,2808.610107,2795.139893,2806.979980,2806.979980,2907430000
2018-07-24,2820.679932,2829.989990,2811.120117,2820.399902,2820.399902,3417530000
2018-07-25,2817.729980,2848.030029,2817.729980,2846.070068,2846.070068,3553010000
2018-07-26,2835.489990,2845.570068,2835.260010,2837.439941,2837.439941,3653330000
2018-07-27,2842.350098,2843.169922,2808.340088,2818.820068,2818.820068,3415710000
2018-07-30,2819.000000,2821.739990,2798.110107,2802.600098,2802.600098,3245770000
2018-07-31,2809.729980,2824.459961,2808.060059,2816.290039,2816.290039,3892100000
2018-08-01,2821.169922,2825.830078,2805.850098,2813.360107,2813.360107,3496990000
2018-08-02,2800.479980,2829.909912,2796.340088,2827.219971,2827.219971,3467380000
2018-08-03,2829.620117,2840.379883,2827.370117,2840.350098,2840.350098,3030390000
2018-08-06,2840.290039,2853.290039,2835.979980,2850.399902,2850.399902,2874540000
2018-08-07,2855.919922,2863.429932,2855.919922,2858.449951,2858.449951,3162770000
2018-08-08,2856.790039,2862.439941,2853.090088,2857.699951,2857.699951,2972200000
2018-08-09,2857.189941,2862.479980,2851.979980,2853.580078,2853.580078,3047050000
2018-08-10,2838.899902,2842.199951,2825.810059,2833.280029,2833.280029,3256040000
2018-08-13,2835.459961,2843.399902,2819.879883,2821.929932,2821.929932,3158450000
2018-08-14,2827.879883,2843.110107,2826.580078,2839.959961,2839.959961,2976970000
2018-08-15,2827.949951,2827.949951,2802.489990,2818.370117,2818.370117,3645070000
2018-08-16,2831.439941,2850.489990,2831.439941,2840.689941,2840.689941,3219880000
2018-08-17,2838.320068,2855.629883,2833.729980,2850.129883,2850.129883,3024100000
2018-08-20,2853.929932,2859.760010,2850.620117,2857.050049,2857.050049,2748020000
2018-08-21,2861.510010,2873.229980,2861.320068,2862.959961,2862.959961,3147140000
2018-08-22,2860.989990,2867.540039,2856.050049,2861.820068,2861.820068,2689560000
2018-08-23,2860.290039,2868.780029,2854.030029,2856.979980,2856.979980,2713910000
2018-08-24,2862.350098,2876.159912,2862.350098,2874.689941,2874.689941,2596190000
2018-08-27,2884.689941,2898.250000,2884.689941,2896.739990,2896.739990,2854080000
2018-08-28,2901.449951,2903.770020,2893.500000,2897.520020,2897.520020,2683190000
2018-08-29,2900.620117,2916.500000,2898.399902,2914.040039,2914.040039,2791860000
2018-08-30,2908.939941,2912.459961,2895.219971,2901.129883,2901.129883,2802180000
2018-08-31,2898.370117,2906.320068,2891.729980,2901.520020,2901.520020,2880260000
2018-09-04,2896.959961,2900.179932,2885.129883,2896.719971,2896.719971,3077060000
2018-09-05,2891.590088,2894.209961,2876.919922,2888.600098,2888.600098,3241250000
2018-09-06,2888.639893,2892.050049,2867.290039,2878.050049,2878.050049,3139590000
2018-09-07,2868.260010,2883.810059,2864.120117,2871.679932,2871.679932,2946270000
2018-09-10,2881.389893,2886.929932,2875.939941,2877.129883,2877.129883,2731400000
2018-09-11,2871.570068,2892.520020,2866.780029,2887.889893,2887.889893,2899660000
2018-09-12,2888.290039,2894.649902,2879.199951,2888.919922,2888.919922,3264930000
2018-09-13,2896.850098,2906.760010,2896.389893,2904.179932,2904.179932,3254930000
2018-09-14,2906.379883,2908.300049,2895.770020,2904.979980,2904.979980,3149800000
2018-09-17,2903.830078,2904.649902,2886.159912,2888.800049,2888.800049,2947760000
2018-09-18,2890.739990,2911.169922,2890.429932,2904.310059,2904.310059,3074610000
2018-09-19,2906.600098,2912.360107,2903.820068,2907.949951,2907.949951,3280020000
2018-09-20,2919.729980,2934.800049,2919.729980,2930.750000,2930.750000,3337730000
2018-09-21,2936.760010,2940.909912,2927.110107,2929.669922,2929.669922,5607610000
2018-09-24,2921.830078,2923.790039,2912.629883,2919.370117,2919.370117,3372210000
2018-09-25,2921.750000,2923.949951,2913.699951,2915.560059,2915.560059,3285480000
2018-09-26,2916.979980,2931.149902,2903.280029,2905.969971,2905.969971,3388620000
2018-09-27,2911.649902,2927.219971,2909.270020,2914.000000,2914.000000,3060850000
2018-09-28,2910.030029,2920.530029,2907.500000,2913.979980,2913.979980,3432300000
2018-10-01,2926.290039,2937.060059,2917.909912,2924.590088,2924.590088,3364190000
2018-10-02,2923.800049,2931.419922,2919.370117,2923.429932,2923.429932,3401880000
2018-10-03,2931.689941,2939.860107,2921.360107,2925.510010,2925.510010,3598710000
2018-10-04,2919.350098,2919.780029,2883.919922,2901.610107,2901.610107,3496860000
2018-10-05,2902.540039,2909.639893,2869.290039,2885.570068,2885.570068,3328980000
2018-10-08,2877.530029,2889.449951,2862.080078,2884.429932,2884.429932,3330320000
2018-10-09,2882.510010,2894.830078,2874.270020,2880.340088,2880.340088,3520500000
2018-10-10,2873.899902,2874.020020,2784.860107,2785.679932,2785.679932,4501250000
2018-10-11,2776.870117,2795.139893,2710.510010,2728.370117,2728.370117,4890630000
2018-10-12,2770.540039,2775.770020,2729.439941,2767.129883,2767.129883,3966040000
2018-10-15,2763.830078,2775.989990,2749.030029,2750.790039,2750.790039,3300140000
2018-10-16,2767.050049,2813.459961,2766.909912,2809.919922,2809.919922,3428340000
2018-10-17,2811.669922,2816.939941,2781.810059,2809.209961,2809.209961,3321710000
2018-10-18,2802.000000,2806.040039,2755.179932,2768.780029,2768.780029,3616440000
2018-10-19,2775.659912,2797.770020,2760.270020,2767.780029,2767.780029,3566490000
2018-10-22,2773.939941,2778.939941,2749.219971,2755.879883,2755.879883,3307140000
2018-10-23,2721.030029,2753.590088,2691.429932,2740.689941,2740.689941,4348580000
2018-10-24,2737.870117,2742.590088,2651.889893,2656.100098,2656.100098,4709310000
2018-10-25,2674.879883,2722.699951,2667.840088,2705.570068,2705.570068,4634770000
2018-10-26,2667.860107,2692.379883,2628.159912,2658.689941,2658.689941,4803150000
2018-10-29,2682.649902,2706.850098,2603.540039,2641.250000,2641.250000,4673700000
2018-10-30,2640.679932,2685.429932,2635.340088,2682.629883,2682.629883,5106380000
2018-10-31,2705.600098,2736.689941,2705.600098,2711.739990,2711.739990,5112420000
2018-11-01,2717.580078,2741.669922,2708.850098,2740.370117,2740.370117,4708420000
2018-11-02,2745.449951,2756.550049,2700.439941,2723.060059,2723.060059,4237930000
2018-11-05,2726.370117,2744.270020,2717.939941,2738.310059,2738.310059,3623320000
2018-11-06,2738.399902,2756.820068,2737.080078,2755.449951,2755.449951,3510860000
2018-11-07,2774.129883,2815.149902,2774.129883,2813.889893,2813.889893,3914750000
2018-11-08,2806.379883,2814.750000,2794.989990,2806.830078,2806.830078,3630490000
2018-11-09,2794.100098,2794.100098,2764.239990,2781.010010,2781.010010,4019090000
2018-11-12,2773.929932,2775.989990,2722.000000,2726.219971,2726.219971,3670930000
2018-11-13,2730.050049,2754.600098,2714.979980,2722.179932,2722.179932,4091440000
2018-11-14,2737.899902,2746.800049,2685.750000,2701.580078,2701.580078,4402370000
2018-11-15,2693.520020,2735.379883,2670.750000,2730.199951,2730.199951,4179140000
2018-11-16,2718.540039,2746.750000,2712.159912,2736.270020,2736.270020,3975180000
2018-11-19,2730.739990,2733.159912,2681.090088,2690.729980,2690.729980,3772900000
2018-11-20,2654.600098,2669.439941,2631.520020,2641.889893,2641.889893,4357900000
2018-11-21,2657.739990,2670.729980,2649.820068,2649.929932,2649.929932,3233550000
2018-11-23,2633.360107,2647.550049,2631.090088,2632.560059,2632.560059,1651650000
2018-11-26,2649.969971,2674.350098,2649.969971,2673.449951,2673.449951,3443950000
2018-11-27,2663.750000,2682.530029,2655.889893,2682.169922,2682.169922,3485220000
2018-11-28,2691.449951,2744.000000,2684.379883,2743.790039,2743.790039,3951670000
2018-11-29,2736.969971,2753.750000,2722.939941,2737.800049,2737.800049,3560770000
2018-11-30,2737.760010,2760.879883,2732.760010,2760.169922,2760.169922,4658580000
2018-12-03,2790.500000,2800.179932,2773.379883,2790.370117,2790.370117,4186060000
2018-12-04,2782.429932,2785.929932,2697.179932,2700.060059,2700.060059,4499840000
2018-12-06,2663.510010,2696.149902,2621.530029,2695.949951,2695.949951,5141470000
2018-12-07,2691.260010,2708.540039,2623.139893,2633.080078,2633.080078,4216690000
2018-12-10,2630.860107,2647.510010,2583.229980,2637.719971,2637.719971,4151030000
2018-12-11,2664.439941,2674.350098,2621.300049,2636.780029,2636.780029,3905870000
2018-12-12,2658.229980,2685.439941,2650.260010,2651.070068,2651.070068,3958890000
2018-12-13,2658.699951,2670.189941,2637.270020,2650.540039,2650.540039,3927720000
2018-12-14,2629.679932,2635.070068,2593.840088,2599.949951,2599.949951,4035020000
2018-12-17,2590.750000,2601.129883,2530.540039,2545.939941,2545.939941,4616350000
2018-12-18,2559.899902,2573.989990,2528.709961,2546.159912,2546.159912,4470880000

In [18]:
etl.tail(data)

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2019-12-24' | '3225.449951' | '3226.429932' | '3220.510010' | '3223.379883' | '3223.379883' | '1296540000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-26' | '3227.199951' | '3240.080078' | '3227.199951' | '3239.909912' | '3239.909912' | '2160680000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-27' | '3247.229980' | '3247.929932' | '3234.370117' | '3240.020020' | '3240.020020' | '2428670000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-30' | '3240.090088' | '3240.919922' | '3216.570068' | '3221.290039' | '3221.290039' | '3013290000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-31' | '3215.179932' | '3231.719971' | '3212.030029' | '3230.780029' | '3230.780029' | '2893810000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+

In [20]:
data2020 = etl.io.csv.fromcsv('./datasets/GSPC_2020.csv')

In [21]:
data2020.display()

2020-01-02,3244.669922,3258.139893,3235.530029,3257.850098,3257.850098,3458250000
2020-01-03,3226.360107,3246.149902,3222.340088,3234.850098,3234.850098,3461290000
2020-01-06,3217.550049,3246.840088,3214.639893,3246.280029,3246.280029,3674070000
2020-01-07,3241.860107,3244.909912,3232.429932,3237.179932,3237.179932,3420380000
2020-01-08,3238.590088,3267.070068,3236.669922,3253.050049,3253.050049,3720890000
2020-01-09,3266.030029,3275.580078,3263.669922,3274.699951,3274.699951,3638390000

In [22]:
data2020.nrows()

186

#### Append the contents of a table to a CSV file

In [26]:
appendcsv(data, './datasets/GSPC_full.csv', write_header=True)

In [27]:
data_full = etl.io.csv.fromcsv('./datasets/GSPC_full.csv')

In [28]:
data_full.display()

Date,Open,High,Low,Close,Adj Close,Volume
2018-01-02,2683.729980,2695.889893,2682.360107,2695.810059,2695.810059,3367250000
2018-01-03,2697.850098,2714.370117,2697.770020,2713.060059,2713.060059,3538660000
2018-01-04,2719.310059,2729.290039,2719.070068,2723.989990,2723.989990,3695260000
2018-01-05,2731.330078,2743.449951,2727.919922,2743.149902,2743.149902,3236620000
2018-01-08,2742.669922,2748.510010,2737.600098,2747.709961,2747.709961,3242650000

In [30]:
data_full.nrows()

503

In [31]:
etl.tail(data_full)

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2019-12-24' | '3225.449951' | '3226.429932' | '3220.510010' | '3223.379883' | '3223.379883' | '1296540000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-26' | '3227.199951' | '3240.080078' | '3227.199951' | '3239.909912' | '3239.909912' | '2160680000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-27' | '3247.229980' | '3247.929932' | '3234.370117' | '3240.020020' | '3240.020020' | '2428670000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-30' | '3240.090088' | '3240.919922' | '3216.570068' | '3221.290039' | '3221.290039' | '3013290000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2019-12-31' | '3215.179932' | '3231.719971' | '3212.030029' | '3230.780029' | '3230.780029' | '2893810000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+

In [32]:
appendcsv(data2020, './datasets/GSPC_full.csv', write_header=False)

In [34]:
data_full.nrows()

689

In [35]:
etl.tail(data_full)

+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| Date         | Open          | High          | Low           | Close         | Adj Close     | Volume       |
+==============+===============+===============+===============+===============+===============+==============+
| '2020-09-22' | '3295.750000' | '3320.310059' | '3270.949951' | '3315.570068' | '3315.570068' | '3963300000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2020-09-23' | '3320.110107' | '3323.350098' | '3232.570068' | '3236.919922' | '3236.919922' | '4364500000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2020-09-24' | '3226.139893' | '3278.699951' | '3209.449951' | '3246.590088' | '3246.590088' | '4599470000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2020-09-25' | '3236.659912' | '3306.879883' | '3228.439941' | '3298.459961' | '3298.459961' | '3792220000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+
| '2020-09-28' | '3333.899902' | '3360.739990' | '3332.909912' | '3351.600098' | '3351.600098' | '3946060000' |
+--------------+---------------+---------------+---------------+---------------+---------------+--------------+

#### Extracting TSV data
https://www.kaggle.com/angfurno/custdata2tsv

In [18]:
customer_data = etl.fromtsv('./datasets/custdata.tsv')

In [19]:
customer_data.display()

custid,sex,is.employed,income,marital.stat,health.ins,housing.type,recent.move,num.vehicles,age,state.of.res
2068,F,NA,11300,Married,TRUE,Homeowner free and clear,FALSE,2,49,Michigan
2848,M,TRUE,4500,Never Married,FALSE,Rented,TRUE,3,22,Georgia
5641,M,TRUE,20000,Never Married,FALSE,Occupied with no rent,FALSE,0,22,New Mexico
6369,F,TRUE,12000,Never Married,TRUE,Rented,TRUE,1,31,Florida
8322,F,TRUE,180000,Never Married,TRUE,Homeowner with mortgage/loan,FALSE,1,40,New York

Return the string values of the header row. If the header row contains only strings, then this function is equivalent to header()

In [38]:
etl.fieldnames(customer_data)

('custid',
 'sex',
 'is.employed',
 'income',
 'marital.stat',
 'health.ins',
 'housing.type',
 'recent.move',
 'num.vehicles',
 'age',
 'state.of.res')

In [39]:
emp_details = etl.fromtext('./datasets/emp_details.txt', header = ['Details'] )

In [40]:
etl.lookall(emp_details)

+-----------------------+
| Details               |
+=======================+
| '1,Alice,Operations'  |
+-----------------------+
| '234,Barry,HR'        |
+-----------------------+
| '321,Carol,Finance'   |
+-----------------------+
| '324,Fran,HR'         |
+-----------------------+
| '654,Harry,Analytics' |
+-----------------------+
| '5526,Erika,Finance'  |
+-----------------------+

strip() function is called on each line, which by default will remove leading and trailing whitespace,
including the end-of-line character

#### Use the capture() method to extract field values
https://petl.readthedocs.io/en/stable/transform.html?highlight=capture#petl.transform.regex.capture

In [41]:
emp_details_table = emp_details.capture('Details', '(.*),(.*),(.*)$',
                                        ['ID', 'Name', 'Department'])

In [40]:
etl.lookall(emp_details_table)

+--------+---------+--------------+
| ID     | Name    | Department   |
+========+=========+==============+
| '1'    | 'Alice' | 'Operations' |
+--------+---------+--------------+
| '234'  | 'Barry' | 'HR'         |
+--------+---------+--------------+
| '321'  | 'Carol' | 'Finance'    |
+--------+---------+--------------+
| '324'  | 'Fran'  | 'HR'         |
+--------+---------+--------------+
| '654'  | 'Harry' | 'Analytics'  |
+--------+---------+--------------+
| '5526' | 'Erika' | 'Finance'    |
+--------+---------+--------------+

In [51]:
template = '''|->
              | {ID}
              | {Name}
              | {Department}'''

In [52]:
epilogue = '|}'

In [53]:
etl.totext(emp_details_table, 
           'emp_details_sample.txt', 
           template=template, 
           epilogue=epilogue)

In [54]:
print(open('emp_details_sample.txt').read())

|->
              | 1
              | Alice
              | Operations|->
              | 234
              | Barry
              | HR|->
              | 321
              | Carol
              | Finance|->
              | 324
              | Fran
              | HR|->
              | 654
              | Harry
              | Analytics|->
              | 5526
              | Erika
              | Finance|}

In [74]:
prologue = '=========START=========\n'

template = '########\n'\
           '{ID} | {Name} | {Department}\n'

epilogue = '=========END========='

In [75]:
etl.totext(emp_details_table, 
           'emp_details_sample.txt', 
           template=template,
           prologue=prologue,
           epilogue=epilogue)

In [76]:
print(open('emp_details_sample.txt').read())

=========START=========
########
1 | Alice | Operations
########
234 | Barry | HR
########
321 | Carol | Finance
########
324 | Fran | HR
########
654 | Harry | Analytics
########
5526 | Erika | Finance
=========END=========

Return a table that writes rows to a text file as they are iterated over

In [47]:
employee_list  = [['Name', 'Id'],
                 ['Charles', 223],
                 ['Fran', 673],
                 ['Harry', 93993],
                 ['Erika', 785]]

In [48]:
template = '''{Name},{Id}\n'''

In [49]:
etl.teetext(employee_list, './datasets/emp_list.txt', template = template)

+-----------+-------+
| Name      | Id    |
+===========+=======+
| 'Charles' |   223 |
+-----------+-------+
| 'Fran'    |   673 |
+-----------+-------+
| 'Harry'   | 93993 |
+-----------+-------+
| 'Erika'   |   785 |
+-----------+-------+

In [50]:
print(open('./datasets/emp_list.txt').read())

Charles,223
Fran,673
Harry,93993
Erika,785