In [1]:
import pandas as pd
import petl as etl

https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data

In [2]:
data_nyc = pd.read_csv('./datasets/AB_NYC_2019.csv')

In [3]:
data = etl.fromdataframe(data_nyc)

In [4]:
data

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 |          -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth'   | 'Manhattan'         | 'Harlem'       | 40.809020000000004 |           -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Select rows meeting a condition

In [5]:
airbnb_brooklyn = etl.select(data, 
                             lambda rec: rec.neighbourhood_group == 'Brooklyn')

In [6]:
airbnb_brooklyn

+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                             | host_id | host_name       | neighbourhood_group | neighbourhood        | latitude           | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+==================================================+=========+=================+=====================+======================+====================+===========+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'             |    2787 | 'John'          | 'Brooklyn'          | 'Kensington'         | 40.647490000000005 | -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                |    4869 | 'LisaRoxanne'   | 'Brooklyn'          | 'Clinton Hill'       | 40.685140000000004 | -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5121 | 'BlissArtsSpace!'                                |    7356 | 'Garon'         | 'Brooklyn'          | 'Bedford-Stuyvesant' |           40.68688 | -73.95596 | 'Private room'    |    60 |             45 |                49 | '05/10/17'  |               0.4 |                              1 |                0 |
+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5803 | 'Lovely Room 1, Garden, Best Area, Legal rental' |    9744 | 'Laurie'        | 'Brooklyn'          | 'South Slope'        |           40.66829 | -73.98779 | 'Private room'    |    89 |              4 |               167 | '24/06/19'  |              1.34 |                              3 |              314 |
+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 6848 | 'Only 2 stops to Manhattan studio'               |   15991 | 'Allen & Irina' | 'Brooklyn'          | 'Williamsburg'       |           40.70837 | -73.95352 | 'Entire home/apt' |   140 |              2 |               148 | '29/06/19'  |               1.2 |                              1 |               46 |
+------+--------------------------------------------------+---------+-----------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [7]:
airbnb_brooklyn.tail()

+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id       | name                                              | host_id   | host_name  | neighbourhood_group | neighbourhood        | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+==========+===================================================+===========+============+=====================+======================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 36482231 | 'Bushwick _ Myrtle-Wyckoff'                       |  66058896 | 'Luisa'    | 'Brooklyn'          | 'Bushwick'           |           40.69652 |          -73.91079 | 'Private room'    |    40 |             20 |                 0 |         nan |               nan |                              1 |               31 |
+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 36482783 | 'Brooklyn Oasis in the heart of Williamsburg'     | 274307600 | 'Jonathan' | 'Brooklyn'          | 'Williamsburg'       |            40.7179 | -73.96238000000001 | 'Private room'    |   190 |              7 |                 0 |         nan |               nan |                              1 |              341 |
+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 36483152 | 'Garden Jewel Apartment in Williamsburg New York' | 208514239 | 'Melki'    | 'Brooklyn'          | 'Williamsburg'       |           40.71232 |           -73.9422 | 'Entire home/apt' |   170 |              1 |                 0 |         nan |               nan |                              3 |              365 |
+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 36484665 | 'Charming one bedroom - newly renovated rowhouse' |   8232441 | 'Sabrina'  | 'Brooklyn'          | 'Bedford-Stuyvesant' |           40.67853 |          -73.94995 | 'Private room'    |    70 |              2 |                 0 |         nan |               nan |                              2 |                9 |
+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 36485057 | 'Affordable room in Bushwick/East Williamsburg'   |   6570630 | 'Marisol'  | 'Brooklyn'          | 'Bushwick'           | 40.701840000000004 | -73.93316999999999 | 'Private room'    |    40 |              4 |                 0 |         nan |               nan |                              2 |               36 |
+----------+---------------------------------------------------+-----------+------------+---------------------+----------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+

In [9]:
etl.nrows(data)

48895

In [10]:
etl.nrows(airbnb_brooklyn)

20104

In [11]:
airbnb_brooklyn_williamsburg = etl.select(data, 
                                          lambda rec: rec.neighbourhood_group == 'Brooklyn'
                                          and rec.neighbourhood == 'Williamsburg')

In [12]:
airbnb_brooklyn_williamsburg

+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                               | host_id | host_name       | neighbourhood_group | neighbourhood  | latitude | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+====================================+=========+=================+=====================+================+==========+====================+===================+=======+================+===================+=============+===================+================================+==================+
|  6848 | 'Only 2 stops to Manhattan studio' |   15991 | 'Allen & Irina' | 'Brooklyn'          | 'Williamsburg' | 40.70837 |          -73.95352 | 'Entire home/apt' |   140 |              2 |               148 | '29/06/19'  |               1.2 |                              1 |               46 |
+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
|  7801 | 'Sweet and Spacious Brooklyn Loft' |   21207 | 'Chaya'         | 'Brooklyn'          | 'Williamsburg' | 40.71842 | -73.95718000000001 | 'Entire home/apt' |   299 |              3 |                 9 | '28/12/11'  |              0.07 |                              1 |                0 |
+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 14290 | '* ORIGINAL BROOKLYN LOFT *'       |   56104 | 'James'         | 'Brooklyn'          | 'Williamsburg' |  40.7042 |           -73.9356 | 'Entire home/apt' |   228 |              3 |                82 | '17/05/19'  |               0.7 |                              1 |              140 |
+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 14377 | 'Williamsburg 1 bedroom Apartment' |   56512 | 'Joanna'        | 'Brooklyn'          | 'Williamsburg' | 40.70881 |           -73.9593 | 'Entire home/apt' |   150 |             30 |               105 | '22/06/19'  |               0.9 |                              1 |               30 |
+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 15385 | 'Very, very cozy place'            |   60252 | 'Cristina'      | 'Brooklyn'          | 'Williamsburg' | 40.71185 |          -73.96204 | 'Private room'    |    80 |              2 |                42 | '30/06/19'  |              0.38 |                              1 |              263 |
+-------+------------------------------------+---------+-----------------+---------------------+----------------+----------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [13]:
etl.nrows(airbnb_brooklyn_williamsburg)

3920

In [18]:
airbnb_brooklyn_wbg_ps = etl.select(data, 
                                    lambda rec: rec.neighbourhood_group == 'Brooklyn'
                                    and (rec.neighbourhood == 'Williamsburg'
                                         or rec.neighbourhood == 'Park Slope'))

In [19]:
airbnb_brooklyn_wbg_ps

+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                               | host_id | host_name       | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================+=========+=================+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 6848 | 'Only 2 stops to Manhattan studio' |   15991 | 'Allen & Irina' | 'Brooklyn'          | 'Williamsburg' |           40.70837 |          -73.95352 | 'Entire home/apt' |   140 |              2 |               148 | '29/06/19'  |               1.2 |                              1 |               46 |
+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 7801 | 'Sweet and Spacious Brooklyn Loft' |   21207 | 'Chaya'         | 'Brooklyn'          | 'Williamsburg' |           40.71842 | -73.95718000000001 | 'Entire home/apt' |   299 |              3 |                 9 | '28/12/11'  |              0.07 |                              1 |                0 |
+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 8024 | 'CBG CtyBGd HelpsHaiti rm#1:1-4'   |   22486 | 'Lisel'         | 'Brooklyn'          | 'Park Slope'   | 40.680690000000006 |          -73.97706 | 'Private room'    |   130 |              2 |               130 | '01/07/19'  |              1.09 |                              6 |              347 |
+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 8025 | 'CBG Helps Haiti Room#2.5'         |   22486 | 'Lisel'         | 'Brooklyn'          | 'Park Slope'   |           40.67989 |          -73.97798 | 'Private room'    |    80 |              1 |                39 | '01/01/19'  |              0.37 |                              6 |              364 |
+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 8110 | 'CBG Helps Haiti Rm #2'            |   22486 | 'Lisel'         | 'Brooklyn'          | 'Park Slope'   | 40.680009999999996 |          -73.97865 | 'Private room'    |   110 |              2 |                71 | '02/07/19'  |              0.61 |                              6 |              304 |
+------+------------------------------------+---------+-----------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [22]:
etl.nrows(airbnb_brooklyn_wbg_ps)

4426

In [23]:
home_airbnb = etl.select(data, 
                         "{room_type} == 'Entire home/apt' and {price} < 250")

In [24]:
home_airbnb

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5099 | 'Large Cozy 1 BR Apartment In Midtown East'        |    7322 | 'Chris'       | 'Manhattan'         | 'Murray Hill'  |           40.74767 |            -73.975 | 'Entire home/apt' |   200 |              3 |                74 | '22/06/19'  |              0.59 |                              1 |              129 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5238 | 'Cute & Cozy Lower East Side 1 bdrm'               |    7549 | 'Ben'         | 'Manhattan'         | 'Chinatown'    | 40.713440000000006 |          -73.99037 | 'Entire home/apt' |   150 |              1 |               160 | '09/06/19'  |              1.33 |                              4 |              188 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [25]:
etl.nrows(home_airbnb)

19790

#### Select rows where the given field equals the given value.

In [26]:
select_neighbourhood = etl.selecteq(data, 'neighbourhood', 'Chinatown')

In [27]:
select_neighbourhood.display()

id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.713440000000006,-73.99037,Entire home/apt,150,1,160,09/06/19,1.33,4,188
59709,"Artistic, Cozy, and Spacious w/ Patio! Sleeps 5",186084,Ricardo & Ashlie,Manhattan,Chinatown,40.71756,-73.99503,Entire home/apt,250,4,18,01/07/19,0.18,2,265
61492,Exclusive Room with Private Bath in LES,297769,Tunji,Manhattan,Chinatown,40.71445,-73.9908,Private room,120,4,171,23/06/19,1.8,2,353
71248,Bright and lovely 1 bdrm apt in LES,363834,Jennifer,Manhattan,Chinatown,40.716590000000004,-73.98945,Entire home/apt,125,25,43,17/06/19,0.42,1,102
204959,Comfortable. Spacious. Private Room.,464506,Ange,Manhattan,Chinatown,40.713,-73.99752,Private room,95,3,172,02/07/19,1.84,2,64

In [28]:
etl.nrows(select_neighbourhood)

368

In [29]:
select_neighbourhood_complement = etl.selecteq(data, 
                                               'neighbourhood', 
                                               'Chinatown', 
                                               complement = True)

In [30]:
select_neighbourhood_complement.display()

id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.647490000000005,-73.97237,Private room,149,1,9,19/10/18,0.21,6,365
2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98376999999999,Entire home/apt,225,1,45,21/05/19,0.38,2,355
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.809020000000004,-73.9419,Private room,150,3,0,nan,nan,1,365
3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.685140000000004,-73.95976,Entire home/apt,89,1,270,05/07/19,4.64,1,194
5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,19/11/18,0.1,1,0

In [31]:
etl.nrows(select_neighbourhood_complement)

48527

#### Select rows where the given field does not equal the given value.

In [32]:
select_private_and_shared_room = etl.selectne(data, 
                                              'room_type', 
                                              'Entire home/apt')

In [33]:
select_private_and_shared_room.display()

id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.647490000000005,-73.97237,Private room,149,1,9,19/10/18,0.21,6,365
3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.809020000000004,-73.9419,Private room,150,3,0,nan,nan,1,365
5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,05/10/17,0.4,1,0
5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,24/06/19,3.47,1,220
5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,21/07/17,0.99,1,0

#### Select rows where the given field contains the given value

In [34]:
manhattan_airbnb = etl.selectcontains(data, 'neighbourhood_group', 'Manhattan')

In [35]:
manhattan_airbnb

+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name   | neighbourhood_group | neighbourhood    | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+=============+=====================+==================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'  | 'Manhattan'         | 'Midtown'        |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth' | 'Manhattan'         | 'Harlem'         | 40.809020000000004 |           -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'     | 'Manhattan'         | 'East Harlem'    |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5099 | 'Large Cozy 1 BR Apartment In Midtown East'        |    7322 | 'Chris'     | 'Manhattan'         | 'Murray Hill'    |           40.74767 |            -73.975 | 'Entire home/apt' |   200 |              3 |                74 | '22/06/19'  |              0.59 |                              1 |              129 |
+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5178 | "Large Furnished Room Near B'way "                 |    8967 | 'Shunichi'  | 'Manhattan'         | "Hell's Kitchen" |           40.76489 |          -73.98493 | 'Private room'    |    79 |              2 |               430 | '24/06/19'  |              3.47 |                              1 |              220 |
+------+----------------------------------------------------+---------+-------------+---------------------+------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### selectcontains scans for substrings and not full matches

In [36]:
east_airbnb = etl.selectcontains(data, 'neighbourhood', 'East')

east_airbnb

+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                               | host_id | host_name | neighbourhood_group | neighbourhood     | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+====================================================+=========+===========+=====================+===================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
|  5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'   | 'Manhattan'         | 'East Harlem'     |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
|  7750 | 'Huge 2 BR Upper East  Cental Park'                |   17985 | 'Sing'    | 'Manhattan'         | 'East Harlem'     |           40.79685 |          -73.94872 | 'Entire home/apt' |   190 |              7 |                 0 |         nan |               nan |                              2 |              249 |
+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
|  9657 | 'Modern 1 BR / NYC / EAST VILLAGE'                 |   21904 | 'Dana'    | 'Manhattan'         | 'East Village'    |            40.7292 | -73.98541999999999 | 'Entire home/apt' |   180 |             14 |                29 | '19/04/19'  |              0.24 |                              1 |               67 |
+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 12048 | 'LowerEastSide apt share shortterm 1'              |    7549 | 'Ben'     | 'Manhattan'         | 'Lower East Side' | 40.714009999999995 |          -73.98917 | 'Shared room'     |    40 |              1 |               214 | '05/07/19'  |              1.81 |                              4 |              188 |
+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 12192 | 'ENJOY Downtown NYC!'                              |   46978 | 'Edward'  | 'Manhattan'         | 'East Village'    |            40.7229 |          -73.98199 | 'Private room'    |    68 |              2 |               245 | '21/06/19'  |              2.08 |                              2 |               96 |
+-------+----------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [38]:
village_airbnb = etl.selectcontains(data, 'neighbourhood', 'Village')

village_airbnb

+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                     | host_id | host_name | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+==========================================+=========+===========+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
|  6090 | 'West Village Nest - Superhost'          |   11975 | 'Alina'   | 'Manhattan'         | 'West Village' |            40.7353 |          -74.00525 | 'Entire home/apt' |   120 |             90 |                27 | '31/10/18'  |              0.22 |                              1 |                0 |
+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
|  9657 | 'Modern 1 BR / NYC / EAST VILLAGE'       |   21904 | 'Dana'    | 'Manhattan'         | 'East Village' |            40.7292 | -73.98541999999999 | 'Entire home/apt' |   180 |             14 |                29 | '19/04/19'  |              0.24 |                              1 |               67 |
+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 12192 | 'ENJOY Downtown NYC!'                    |   46978 | 'Edward'  | 'Manhattan'         | 'East Village' |            40.7229 |          -73.98199 | 'Private room'    |    68 |              2 |               245 | '21/06/19'  |              2.08 |                              2 |               96 |
+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 16580 | 'Sunny, Modern room in East Village!'    |   64442 | 'Reka'    | 'Manhattan'         | 'East Village' | 40.726490000000005 |          -73.97904 | 'Private room'    |    80 |              1 |               338 | '01/07/19'  |              4.72 |                              2 |               72 |
+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 16821 | 'Large Room in Amazing East Village Apt' |    4396 | 'Casey'   | 'Manhattan'         | 'East Village' |           40.72298 |          -73.98474 | 'Private room'    |    99 |              1 |               106 | '21/06/19'  |              1.26 |                              2 |              336 |
+-------+------------------------------------------+---------+-----------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### The search is case sensitive

In [39]:
village_airbnb = etl.selectcontains(data, 'neighbourhood', 'village')

village_airbnb

+----+------+---------+-----------+---------------------+---------------+----------+-----------+-----------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id | name | host_id | host_name | neighbourhood_group | neighbourhood | latitude | longitude | room_type | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+====+======+=========+===========+=====================+===============+==========+===========+===========+=======+================+===================+=============+===================+================================+==================+

#### Select rows where the given field is a member of the given value

In [40]:
airbnb_queens = etl.selectin(data, 'neighbourhood_group', 'Queens')

In [41]:
airbnb_queens

+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                                 | host_id | host_name | neighbourhood_group | neighbourhood      | latitude | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+======================================================+=========+===========+=====================+====================+==========+===========+===================+=======+================+===================+=============+===================+================================+==================+
| 12937 | '1 Stop fr. Manhattan! Private Suite,Landmark Block' |   50124 | 'Orestes' | 'Queens'            | 'Long Island City' | 40.74771 |  -73.9474 | 'Private room'    |   130 |              3 |               248 | '01/07/19'  |              2.25 |                              1 |              215 |
+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 18198 | 'Little King of Queens'                              |   70091 | 'Justin'  | 'Queens'            | 'Woodside'         | 40.75038 | -73.90334 | 'Private room'    |    70 |             30 |                25 | '31/05/19'  |              0.22 |                              1 |              324 |
+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 32363 | 'Fully Furnished Basement Apartment'                 |  140025 | 'Fredah'  | 'Queens'            | 'Flushing'         | 40.74028 | -73.83168 | 'Private room'    |   140 |              2 |                 1 | '19/09/11'  |              0.01 |                              1 |                1 |
+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 39593 | 'A room w/ a Manhattan view, longer stay'            |  110506 | 'Myung'   | 'Queens'            | 'Sunnyside'        | 40.74559 | -73.92313 | 'Private room'    |    79 |             30 |                28 | '12/04/19'  |              0.26 |                              1 |              126 |
+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 45910 | 'Beautiful Queens Brownstone! - 5BR'                 |  204539 | 'Mark'    | 'Queens'            | 'Ridgewood'        | 40.70382 | -73.89797 | 'Entire home/apt' |   350 |              8 |                10 | '12/05/19'  |              0.11 |                              5 |              365 |
+-------+------------------------------------------------------+---------+-----------+---------------------+--------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [42]:
airbnb_except_bronx = etl.selectnotin(data, 'neighbourhood_group', 'Bronx')

In [43]:
airbnb_except_bronx

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 |          -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth'   | 'Manhattan'         | 'Harlem'       | 40.809020000000004 |           -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [44]:
etl.nrows(airbnb_except_bronx)

47804

#### Select rows where the given field is less than the given value.

In [45]:
affordable_airbnb = etl.selectlt(data, 'price', 200)

In [46]:
affordable_airbnb

+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood        | latitude           | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+======================+====================+===========+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'         | 40.647490000000005 | -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth'   | 'Manhattan'         | 'Harlem'             | 40.809020000000004 |  -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill'       | 40.685140000000004 | -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'        |           40.79851 | -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5121 | 'BlissArtsSpace!'                                  |    7356 | 'Garon'       | 'Brooklyn'          | 'Bedford-Stuyvesant' |           40.68688 | -73.95596 | 'Private room'    |    60 |             45 |                49 | '05/10/17'  |               0.4 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [47]:
etl.nrows(affordable_airbnb)

39110

#### Select rows where the given field is greater than or equal to the given value.

In [48]:
expensive_airbnb = etl.selectge(data, 'price', 900)

In [49]:
expensive_airbnb

+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id     | name                                               | host_id | host_name      | neighbourhood_group | neighbourhood     | latitude | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+========+====================================================+=========+================+=====================+===================+==========+===========+===================+=======+================+===================+=============+===================+================================+==================+
| 174966 | 'Luxury 2Bed/2.5Bath Central Park View'            |  836168 | 'Henry'        | 'Manhattan'         | 'Upper West Side' |  40.7735 | -73.98697 | 'Entire home/apt' |  2000 |             30 |                30 | '05/05/18'  |              0.33 |                             11 |                0 |
+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 273190 | '6 Bedroom Landmark West Village Townhouse'        |  605463 | 'West Village' | 'Manhattan'         | 'West Village'    | 40.73301 | -74.00268 | 'Entire home/apt' |  1300 |              5 |                28 | '25/09/18'  |              0.31 |                              4 |              297 |
+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 363673 | 'Beautiful 3 bedroom in Manhattan'                 |  256239 | 'Tracey'       | 'Manhattan'         | 'Upper West Side' | 40.80142 | -73.96931 | 'Private room'    |  3000 |              7 |                 0 |         nan |               nan |                              1 |              365 |
+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 468613 | '$ (Phone number hidden by Airbnb) weeks - room f' | 2325861 | 'Cynthia'      | 'Manhattan'         | 'Lower East Side' | 40.72152 | -73.99279 | 'Private room'    |  1300 |              1 |                 0 |         nan |               nan |                              1 |                0 |
+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 634353 | 'Luxury 1Bed with Central Park Views'              |  836168 | 'Henry'        | 'Manhattan'         | 'Upper West Side' | 40.77428 | -73.98594 | 'Entire home/apt' |  1000 |             30 |                44 | '28/09/15'  |              0.53 |                             11 |              364 |
+--------+----------------------------------------------------+---------+----------------+---------------------+-------------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Select rows where the given field is greater than or equal to minv and less than or equal to maxv

In [50]:
medium_priced_airbnb = etl.selectrangeopen(data, 'price', 250, 500)

In [51]:
medium_priced_airbnb

+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                                 | host_id | host_name | neighbourhood_group | neighbourhood     | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+======================================================+=========+===========+=====================+===================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
|  7801 | 'Sweet and Spacious Brooklyn Loft'                   |   21207 | 'Chaya'   | 'Brooklyn'          | 'Williamsburg'    |           40.71842 | -73.95718000000001 | 'Entire home/apt' |   299 |              3 |                 9 | '28/12/11'  |              0.07 |                              1 |                0 |
+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 15396 | 'Sunny & Spacious Chelsea Apartment'                 |   60278 | 'Petra'   | 'Manhattan'         | 'Chelsea'         |           40.74623 |           -73.9953 | 'Entire home/apt' |   375 |            180 |                 5 | '03/11/18'  |              0.12 |                              1 |              180 |
+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 15711 | '2 bedroom - Upper East Side-great for kids'         |   61491 | 'D'       | 'Manhattan'         | 'Upper East Side' |           40.77065 |          -73.95269 | 'Entire home/apt' |   250 |              2 |                66 | '30/03/19'  |              0.57 |                              2 |              231 |
+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 16595 | '*HAVEN LOFT - Entire Floor - Six Windows - Bricks*' |   64522 | 'Daniel'  | 'Brooklyn'          | 'Williamsburg'    |           40.70933 | -73.96791999999999 | 'Entire home/apt' |   275 |              1 |               148 | '23/06/19'  |               1.4 |                              1 |              362 |
+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 19169 | 'Entire 2 Bedroom - Large & Sunny'                   |   73128 | 'JoLynn'  | 'Manhattan'         | 'Lower East Side' | 40.718509999999995 |          -73.98892 | 'Entire home/apt' |   285 |              5 |                70 | '30/06/19'  |              0.62 |                              1 |              328 |
+-------+------------------------------------------------------+---------+-----------+---------------------+-------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Select rows where the given field is greater than or equal to minv and less than maxv

In [52]:
highly_reviewed = etl.selectrangeopenleft(data, 'number_of_reviews', 401, 630)

In [53]:
highly_reviewed

+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                                 | host_id | host_name        | neighbourhood_group | neighbourhood    | latitude           | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+======================================================+=========+==================+=====================+==================+====================+===========+===================+=======+================+===================+=============+===================+================================+==================+
|  5178 | "Large Furnished Room Near B'way "                   |    8967 | 'Shunichi'       | 'Manhattan'         | "Hell's Kitchen" |           40.76489 | -73.98493 | 'Private room'    |    79 |              2 |               430 | '24/06/19'  |              3.47 |                              1 |              220 |
+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 26785 | 'Park Slope Green Guest House'                       |   42273 | 'Dani'           | 'Brooklyn'          | 'South Slope'    |           40.66853 | -73.98912 | 'Entire home/apt' |   120 |             30 |               467 | '30/12/18'  |              4.22 |                              2 |              192 |
+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 31994 | 'Room with En Suite Bathroom & Deck'                 |  137814 | 'Waldemar'       | 'Brooklyn'          | 'Clinton Hill'   |            40.6873 |  -73.9634 | 'Private room'    |    76 |              2 |               426 | '24/06/19'  |              3.89 |                              3 |              275 |
+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 58059 | 'PRIVATE Room on Historic Sugar Hill'                |  277379 | 'Agnes'          | 'Manhattan'         | 'Harlem'         |            40.8251 | -73.94287 | 'Private room'    |    60 |              1 |               458 | '03/07/19'  |              4.58 |                              2 |              258 |
+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 63360 | 'Safe cute near subway& Manhattan NY NY retro style' |  307962 | 'Dennis & Naoko' | 'Queens'            | 'Astoria'        | 40.753840000000004 | -73.91433 | 'Entire home/apt' |    99 |              5 |               441 | '24/06/19'  |               4.5 |                              1 |              226 |
+-------+------------------------------------------------------+---------+------------------+---------------------+------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [54]:
data

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 |          -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth'   | 'Manhattan'         | 'Harlem'       | 40.809020000000004 |           -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Select rows where the given field is an instance of the given type.

In [55]:
drop_nan_date = etl.selectisinstance(data, 'last_review', str)

In [56]:
drop_nan_date

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 |          -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5099 | 'Large Cozy 1 BR Apartment In Midtown East'        |    7322 | 'Chris'       | 'Manhattan'         | 'Murray Hill'  |           40.74767 |            -73.975 | 'Entire home/apt' |   200 |              3 |                74 | '22/06/19'  |              0.59 |                              1 |              129 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [57]:
select_none = etl.selectnone(data, 'reviews_per_month')

In [58]:
select_none

+----+------+---------+-----------+---------------------+---------------+----------+-----------+-----------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id | name | host_id | host_name | neighbourhood_group | neighbourhood | latitude | longitude | room_type | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+====+======+=========+===========+=====================+===============+==========+===========+===========+=======+================+===================+=============+===================+================================+==================+

#### return a dictionary mapping field values to tables

In [59]:
data = etl.convert(data, 'host_name', str)

In [60]:
host_name = etl.facet(data, 'host_name')

In [62]:
type(host_name)

dict

In [61]:
sorted(host_name.keys())

['#NAME?',
 "'Cil",
 '(Ari) HENRY LEE',
 '(Email hidden by Airbnb)',
 '(Mary) Haiy',
 '123',
 '2018Serenity',
 '371',
 '475',
 '5 Star Stays',
 '@ Art House Monique',
 'A',
 'A & H',
 'A Tree Grows In Brooklyn',
 'A-B',
 'A. Kaylee',
 'A. Nicholas',
 'A.B.',
 'A.J.',
 'A.M',
 'A.R.',
 'AFI Apartments',
 'AGood',
 'AHm',
 'AJ And Freddy',
 'Aaash',
 'Aakash',
 'Aalap',
 'Aamir',
 'Aamito',
 'Aanchal',
 'Aandrea',
 'Aaron',
 'Aaron & Ivy',
 'Aaron Paul',
 'Abayomi',
 'Abbey',
 'Abbi',
 'Abbie',
 'Abbott',
 'Abby',
 'Abby & Kurt',
 'Abc',
 'Abcstay',
 'Abdes',
 'Abdiaziz',
 'Abdirazak',
 'Abdoulaye',
 'Abdul',
 'Abdul Fattah',
 'Abdul Kader',
 'Abdul Rahman',
 'Abdulla',
 'Abdur',
 'Abe',
 'Abe & Gail',
 'Abee',
 'Abeer',
 'Abel',
 'Abella',
 'Abena',
 'Abeni',
 'Abeyu',
 'Abhi',
 'Abhilasha Ashiv',
 'Abhinaya',
 'Abhishek',
 'Abi',
 'Abie',
 'Abigael',
 'Abigail',
 'Abimbola',
 'Abinav',
 'Abir',
 'Abosede',
 'Aboubakar',
 'Abra & Domenic',
 'Abraham',
 'Abram',
 'Abrm',
 'Abshan',
 'Aby',
 'Ac',
 'Acadia',
 'Acclaimed',
 'Ace',
 'Ada',
 'Ada Azra',
 'Adam',
 'Adam & Allen',
 'Adam & Kath',
 'Adam + Yulu',
 'Adam And Ana',
 'Adam And Charity',
 'Adama',
 'Adar',
 'Addie',
 'Ade',
 'Adedayo',
 'Adedeji',
 'Adeel',
 'Adel',
 'Adela',
 'Adelaida',
 'Adelaide',
 'Adele',
 'Adelina',
 'Adelle',
 'Aden',
 'Adena',
 'Adeola',
 'Adero',
 'Adesh & Viviana',
 'Adesola',
 'Adetoro',
 'Adetutu',
 'Adeyemi',
 'Adham',
 'Adhat',
 'Adi',
 'Adi & Naor',
 'Adi And Evangel',
 'Adil',
 'Adila',
 'Adina',
 'Adir',
 'Adishwar',
 'Adisson',
 'Aditi',
 'Aditya',
 'Admir',
 'Adolfo',
 'Adonis',
 'Adonna',
 'Adora',
 'Adreanna',
 'Adreinne',
 'Adria',
 'Adria Hotel & Conference Center',
 'Adriaan',
 'Adrian',
 'Adriana',
 'Adrianna',
 'Adrianne',
 'Adriano',
 'Adriel',
 'Adrien',
 'Adrienne',
 'Adrienne Miriam',
 'Adrián',
 'Ady',
 'Adé',
 'Aendel',
 'Afaliah',
 'Afnan',
 'Afrah',
 'Afrodite',
 'Afshan',
 'Aga',
 'Agata',
 'Agate',
 'Agatha',
 'Agathe',
 'Agathe Et Francois',
 'Agel',
 'Agnes',
 'Agnese',
 'Agnieszka',
 'Agona',
 'Agostina',
 'Agraj',
 'Agus',
 'Agustin',
 'Agustina',
 'Ahlem',
 'Ahmad',
 'Ahmed',
 'Ahmet',
 'Ahna',
 'Ahnastasia',
 'Ahsan',
 'Ahyoung',
 'Ai',
 'Aiana',
 'Aicha',
 'Aida',
 'Aidan',
 'Aidana',
 'Aidas',
 'Aiden & Cassy',
 'Aidin',
 'Aiesha & Stacy',
 'Aigerim Aika',
 'Aigner',
 'Aiko',
 'Ailee',
 'Aileen',
 'Ailin',
 'Aimar',
 'Aimee',
 'Aimée',
 'Aine',
 'Ainsley',
 'Ainslie And John',
 'Airamis',
 'Airik',
 'Aishah',
 'Aishling',
 'Aisling',
 'Aislyn',
 'Aissa',
 'Aissatou',
 'Aitan',
 'Aivars',
 'Aixa',
 'Aiya',
 'Aj',
 'Ajamu',
 'Ajang',
 'Ajay',
 'Ajmol',
 'Ajna',
 'Aka',
 'Aka Times Square',
 'Akari',
 'Akash',
 'Akeem',
 'Akeema',
 'Akem & Terry',
 'Akemi',
 'Aki',
 'Akiea',
 'Akiko',
 'Akil',
 'Akim',
 'Akini',
 'Akinwole',
 'Akira',
 'Akiva',
 'Akm',
 'Akon',
 'Akram',
 'Akriti',
 'Aksa',
 'Aksel',
 'Akshay',
 'Aktina',
 'Al',
 'Al-',
 'Al-Nisa',
 'Ala',
 'Alaa',
 'Alaethia',
 'Alain',
 'Alaina',
 'Alan',
 'Alan And Beckie',
 'Alana',
 'Alanah',
 'Alankrit',
 'Alanna',
 'Alaor',
 'Alarape',
 'Alayna',
 'Alaz',
 'Alba',
 'Alba & Genesis',
 'Albane',
 'Albeiro Y Katalina',
 'Albena',
 'Albert',
 'Alberth',
 'Albertina',
 'Alberto',
 'Albina',
 'Alci',
 'Alcira',
 'Alda',
 'Alden',
 'Aldi',
 'Aldo',
 'Aldric',
 'Ale',
 'Ale And Tom',
 'Alea',
 'Alec',
 'Alec & Laura',
 'Aleecea',
 'Alegria',
 'Aleida',
 'Aleisha',
 'Alejandra',
 'Alejandro',
 'Alejo',
 'Alek',
 'Aleks',
 'Aleksandar',
 'Aleksandr',
 'Aleksandra',
 'Aleksei',
 'Aleksej',
 'Aleksey',
 'Alen',
 'Alena',
 'Alena Devi',
 'Alenka',
 'Alesandra',
 'Alesh',
 'Alesia',
 'Alessandra',
 'Alessandro',
 'Alessia',
 'Alessio',
 'Aleszea',
 'Alex',
 'Alex & Alena',
 'Alex & Britta',
 'Alex & Dave',
 'Alex & Family',
 'Alex & Laura',
 'Alex & Yoly',
 'Alex And Lindsey',
 'Alex And Maya',
 'Alex And Mila',
 'Alex And Tatiana',
 'Alex And Tom',
 'Alex And Zeena',
 'Alex G',
 'Alex Nova York',
 'Alex&Ivy',
 'Alexa',
 'Alexana',
 'Alexander',
 'Alexander M',
 'Alexandr',
 'Alexandra',
 'Alexandra & William',
 'Alexandra-Katherine',
 'Alexandre',
 'Alexandria',
 'Alexandrinho',
 'Alexei',
 'Alexes',
 'Alexey',
 'Alexi',
 'Alexia',
 'Alexie',
 'Alexis',
 'Alexisz Tamás',
 'Alexo & JC',
 'Alexsandro',
 'Alexsis',
 'Alfie',
 'Alfonso',
 'Alfred',
 'Alfred And Lau',
 'Alfredo',
 'Algerchaabi',
 'Algin',
 'Ali',
 'Ali & Guillaume',
 'Ali & SweetPea',
 'Ali And Amy',
 'Ali Nicole',
 'Ali+Scott',
 'Alia',
 'Alican',
 'Alice',
 'Alicia',
 'Alicia And Jamie',
 'Alicia And Zach',
 'Alicja',
 'Alida',
 'Alienor',
 'Aliesha',
 'Alihan',
 'Alik',
 'Alimah',
 'Alin',
 'Alina',
 'Aline',
 'Alinka',
 'Aliona',
 'Alis',
 'Alisa',
 'Alisa & Dante',
 'Alisha',
 'Alison',
 'Alissa',
 'Alissandra',
 'Alistair',
 'Alister',
 'Aliu',
 'Alix',
 'Alixandra',
 'Aliya',
 'Aliza',
 'Alizaveta',
 'Alizee',
 'Alizé',
 'Aljosha',
 'Alkhadher',
 'Alla',
 'Allam',
 'Allan',
 'Allan (& Max)',
 'Allan C.',
 'Allegra',
 'Allen',
 'Allen & Irina',
 'Alley',
 'Alleyne',
 'Alli',
 'Allia',
 'Allie',
 'Alliot',
 'Allison',
 'Allon',
 'Ally',
 'Allyson',
 'Allyssa',
 'Almog',
 'Alo',
 'Alon',
 'Alon & Adi',
 'Alona',
 'Alonso',
 'Alonzo',
 'Alosha',
 'Alourdes',
 'Alpana',
 'Alper',
 'Alper Demis',
 'Alphanso',
 'Alta',
 'Althea',
 'Altin',
 'Alva',
 'Alvaro',
 'Alvaro Luis',
 'Alvin',
 'Alvina',
 'Alvina Da Silva',
 'Alvise',
 'Alwin',
 'Alwyn',
 'Aly',
 'Alyandry',
 'Alycen',
 'Alyona',
 'Alyse',
 'Alysee',
 'Alysha',
 'Alyshia',
 'Alyson',
 'Alyss',
 'Alyssa',
 'Alyssa Faye',
 'Alysse',
 'Alyssia',
 'Am',
 'Amaad',
 'Amadeus',
 'Amado',
 'Amadou',
 'Amael',
 'Amah Justin',
 'Amal',
 'Amal & Alex',
 'Amal & Emad',
 'Amalia',
 'Aman',
 'Amanda',
 'Amanda & Rafael',
 'Amanda Brooke',
 'Amanda Haowei',
 'Amanda Reil',
 'Amanda Rose',
 'Amandine',
 'Amani',
 'Amapola',
 'Amar',
 'Amara',
 'Amardeep',
 'Amaree',
 'Amarie2131',
 'Amarjit S',
 'Amarsana',
 'Amaru',
 'Amaryllis',
 'Amaury',
 'Amaurys',
 'Amaya',
 'Amber',
 'Amber+Shawn',
 'Amberjade',
 'Ambika',
 'Ambre',
 'Ambria',
 'Ambrose And Florence',
 'Ame',
 'Amedeo',
 'Ameer',
 'Ameera',
 'Ameet',
 'Ameira',
 'Amel',
 'Amelia',
 'Amelie & Pascal',
 'Amenee',
 'Amer',
 'Amey',
 'Ameyo',
 'Amhalise',
 'Ami',
 'Amia',
 'Amie',
 'Amiee',
 'Amikole',
 'Amin',
 'Amina',
 'Aminata Mody',
 'Amine',
 'Aminul',
 'Amir',
 'Amira',
 'Amirhos',
 'Amit',
 'Amit & Sofie',
 'Amita',
 'Amitai',
 'Amith',
 'Amitis',
 'Amjad',
 'Amma',
 'Ammy',
 'Amna',
 'Amo',
 'Amon',
 'Amore',
 'Amory',
 'Amos',
 'Amos Rothschild',
 'Amoyiem',
 'Amp',
 'Amparo',
 'Amrane',
 'Amri',
 'Amro',
 'Amruta',
 'Amy',
 'Amy & Brian',
 'Amy-JPSU',
 'Amyt',
 'Amz',
 'Amélie',
 'Amílcar',
 'An',
 'Ana',
 'Ana Bess',
 'Ana Carolina',
 'Ana Corina',
 'Ana Cristina',
 'Ana Luiza',
 'Ana Maria',
 'Ana María',
 'Ana Paula',
 'Ana Sofia',
 'Ana Sophia',
 'Ana Y Hugo',
 'Ana Y Victor',
 'Anabel',
 'Anabell',
 'Anabella',
 'Anabelle',
 'Anada',
 'Anael',
 'Anais',
 'Anaiya',
 'Analia',
 'Analisa',
 'Analise',
 'Anallely',
 'Analá',
 'Anamaria',
 'Anamaria & Ricardo',
 'Anand',
 'Ananth',
 'Anas',
 'Anasha',
 'Anastacia',
 'Anastasia',
 'Anastasia & Jeremy',
 'Anastasia (Tess)',
 'Anastasiia',
 'Anastasios',
 'Anastassia',
 'Anat',
 'Anatha Angèle',
 'Anayah',
 'Anaïs',
 'Anchal',
 'Anchor',
 'Anda',
 'Anders',
 'Anderson',
 'Andi',
 'Andie',
 'Andjela',
 'Andom',
 'Andra',
 'Andrada And Alex',
 'Andraz',
 'Andre',
 'Andrea',
 'Andrea & James',
 'Andreas',
 'Andreas & Bella',
 'Andreas Per Daniel',
 'Andrei',
 'Andreias',
 'Andres',
 'Andres & Mapa',
 'Andres And Salina',
 'Andres Mekos',
 'Andres&Ine',
 'Andressa',
 'Andrew',
 'Andrew & Markus',
 'Andrew & Mary',
 'Andrew And Clara',
 'Andrew And Coline',
 'Andrew And Kat',
 'Andrew And Katie',
 'Andrew And Stine',
 'Andrew And Talia',
 'Andrew M.',
 'Andrew T',
 'Andrey',
 'Andria',
 'Andrian',
 'Andriana',
 'Andrij',
 'Andris',
 'Andriy',
 'Andrzej',
 'André',
 'Andrée',
 'Andrés',
 'Andy',
 'Andy & Friends',
 'Andy & Kiera',
 'Andy And TJ',
 'Aneel',
 'Aneela',
 'Anela',
 'Anelcia Carolle',
 'Aneta',
 'Ang',
 'Ange',
 'Angel',
 'Angela',
 'Angele',
 'Angeles',
 'Angelica',
 'Angelica And Prescott',
 'Angelie',
 'Angelika',
 'Angelina',
 'Angeline',
 'Angelita',
 'Angella',
 'Angelle',
 'Angelo',
 'Angely',
 'Angie',
 'Angie And Matthew',
 'Angus',
 'Angélique',
 'Anh',
 'Anh & David',
 'Anhad',
 'Ani',
 'Ania',
 'Anika',
 'Aniko',
 'Anila',
 'Anima',
 'Anique',
 'Anish',
 'Anisha',
 'Anisia',
 'Anissa',
 'Anita',
 'Anita-Kay',
 'Anitra And Steven',
 'Anja',
 'Anjela',
 'Anjelica',
 'Anjeza',
 'Anjulika',
 'Anka',
 'Ankeen',
 'Ankit',
 'Ankita',
 'Ankur',
 'Ankush',
 'Anmarie',
 'Ann',
 'Ann Marie',
 'AnnMarie',
 'Anna',
 'Anna & Ben',
 'Anna & Frank',
 'Anna & Keith',
 'Anna + Brad',
 'Anna + Fred',
 'Anna + Jason',
 'Anna B',
 'Anna Chiara',
 'Anna Laura',
 'Anna Leah',
 'Anna Lien',
 'Anna Marie',
 'Anna Meng',
 'Anna-Kay',
 'Anna/Fonzy',
 'Anna/Phillip',
 'Annabel',
 'Annabella',
 'Annabelle',
 'Annajan',
 'Annalisa',
 'Annalise',
 'Annalyn',
 'Annamaria',
 'Anndean',
 'Anne',
 'Anne & Gary',
 'Anne A',
 'Anne Ashley',
 'Anne Marie',
 'Anne& Peter',
 'Anne-Charlotte',
 'Anne-Katrin',
 'Anne-Laure',
 'Anne-Laure And Enrique',
 'Anne-Lise',
 'Anne-Marie',
 'Anne-Sophie',
 'Anneka',
 'Annelise',
 'Annero',
 'Annesha',
 'Annesofie',
 'Anneta',
 'Annett',
 'Annett And Chuck',
 'Annette',
 'Annette C',
 'Anni',
 'Annick',
 'Annie',
 'Annie And Joan',
 'Annie Lawrence',
 'Annie Veronique',
 'Annika',
 'Annmarie',
 'Anny',
 'Anokhi',
 'Anoop',
 'Anoush',
 'Anoushka',
 'Anqi',
 'Anselmo',
 'Anshu',
 'Anshul',
 'Anslo',
 'Ant',
 'Antal',
 'Anthony',
 'Anthony And Laura',
 'Anthony J',
 'Anthony Michel',
 'Anthony/Joanne',
 'Antia',
 'Antina',
 'Anting',
 'Antje',
 'Antoaneta',
 'Antoine',
 'Antoinette',
 'Anton',
 'Antonella',
 'Antong',
 'Antonia',
 'Antonieta',
 'Antonio',
 'Antonio José',
 'Antonis',
 'Antony',
 'Antonya',
 'Antonín',
 'Antrice',
 'Antwoine',
 'Anu',
 'Anu -Nicole',
 'Anu-Raga',
 'Anuar',
 'Anuj',
 'Anuja',
 'Anup',
 'Anupam',
 'Anush',
 'Anusheh',
 'Anushua',
 'Anwar',
 'Any',
 'Anya',
 'Anya & Marco',
 'Aoife',
 'Août',
 'Ap',
 'Aparna',
 'Apeksha',
 'Apic',
 'Apollo',
 'Aponte & Tat',
 'Apostle John',
 'Apostolos',
 'Apple',
 'April',
 'April & Tom',
 'April G',
 'Aprilene',
 'Aprill',
 'Aqila',
 'Ara',
 'Aracelis',
 'Aracelli',
 'Aracely',
 'Aralis',
 'Aram',
 'Aramis',
 'Arantza',
 'Arash',
 'Arata',
 'Aravind',
 'Arber',
 'Archie',
 'Arda',
 'Ardeana',
 'Arden',
 'Ardinia',
 'Ardis',
 'Arek',
 'Arelis',
 'Argelis',
 'Ari',
 'Ari And Irin',
 'Aria',
 'Ariadna',
 'Arian',
 'Ariana',
 'Ariane',
 'Arianna',
 'Arianna & Z',
 'Arianne',
 'Aric',
 'Ariel',
 'Ariela',
 'Ariella',
 'Arielle',
 'Arika',
 'Arikia',
 'Arin',
 'Arina',
 'Aris',
 'Aristides',
 'Arjang',
 'Arjay',
 'Arjun',
 'Arkadiy',
 'Arkady',
 'Arkell',
 'Arlen',
 'Arlene',
 'Arleta',
 'Arlette',
 'Arline',
 'Arman',
 'Armando',
 'Armando Rafael',
 'Armel',
 'Armelle',
 'Armen',
 'Armin',
 'Armine',
 'Armstrong',
 'Arnab',
 'Arnan & Zahira',
 'Arnaud',
 'Arnell',
 'Arnie',
 'Arno',
 'Arnol',
 'Arnold',
 'Aron',
 'Arosha',
 'Arpan',
 'Arpit',
 'Arq',
 'Arsen',
 'Arsenio',
 'Arshiya',
 'Art',
 'Artem',
 'Artemis',
 'Artemisia',
 'Artez',
 'Arthouse Hotel',
 'Arthur',
 'Arti',
 'Artie',
 'Artnell',
 'Artur',
 'Arturo',
 'Arty',
 'Arun',
 'Arva',
 'Arya',
 'Aryanna',
 'Aryeh',
 'Aryn',
 'Aryuna',
 'Arza',
 'Asa',
 'Asad',
 'Asaf',
 'Asal',
 'Aseel',
 'Asem',
 'Asema',
 'Asger',
 'Ash',
 'Asha',
 'Ashante',
 'Asheera',
 'Ashek',
 'Asher',
 'Ashfia & Amir',
 'Ashia',
 'Ashish',
 'Ashkon',
 'Ashlee',
 'Ashleigh',
 'Ashley',
 'Ashley & Nate',
 'Ashley & Nir',
 'Ashley And Cayla',
 'Ashley At Bedly',
 'Ashli',
 'Ashlin',
 'Ashly',
 'Ashraf',
 'Ashraful',
 'Ashton',
 'Ashumi',
 'Asi',
 'Asia',
 'Asia Joanna',
 'Asif',
 'Asijah',
 'Asil',
 'Asim',
 'Askhat',
 'Asli',
 'Aspano',
 'Aspen',
 'Assaf',
 'Assane',
 'Asshur',
 'Assiati',
 'Assol',
 'Asta',
 'Aston',
 'Astor',
 'Astoria',
 'Astrid',
 'Asuka',
 'Aswad',
 'Aswini',
 'Asya',
 'Atanas',
 'Athelstan',
 'Athena',
 'Atherly',
 'Athina',
 'Atif',
 'Atiya',
 ...]

In [64]:
host_name['Ady']

+----------+-----------------------------------------------------+-----------+-----------+---------------------+---------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id       | name                                                | host_id   | host_name | neighbourhood_group | neighbourhood | latitude | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+==========+=====================================================+===========+===========+=====================+===============+==========+===========+===================+=======+================+===================+=============+===================+================================+==================+
| 32506530 | 'VERY LARGE NEW STUDIO+LARGE SLEEPING LOFT+DOORMAN' | 243614369 | 'Ady'     | 'Manhattan'         | 'Midtown'     | 40.74757 | -73.98564 | 'Entire home/apt' |   145 |              3 |                 7 | '05/07/19'  |              2.88 |                              1 |               36 |
+----------+-----------------------------------------------------+-----------+-----------+---------------------+---------------+----------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+

In [65]:
host_name['John']

+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id     | name                                          | host_id | host_name | neighbourhood_group | neighbourhood       | latitude           | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+========+===============================================+=========+===========+=====================+=====================+====================+===========+===================+=======+================+===================+=============+===================+================================+==================+
|   2539 | 'Clean & quiet apt home by the park'          |    2787 | 'John'    | 'Brooklyn'          | 'Kensington'        | 40.647490000000005 | -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 148201 | 'NYC - Sunny Greenwich Village 1br'           |  715807 | 'John'    | 'Manhattan'         | 'Greenwich Village' |           40.72831 | -74.00177 | 'Entire home/apt' |   175 |              3 |                18 | '31/05/13'  |              0.19 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 234870 | 'Private Room With GREAT Location'            | 1229984 | 'John'    | 'Queens'            | 'Long Island City'  |           40.74581 | -73.95295 | 'Private room'    |    75 |             30 |                65 | '31/07/17'  |              0.74 |                              3 |              219 |
+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 400039 | 'Big Beautiful Railroad in Brooklyn'          | 1488809 | 'John'    | 'Brooklyn'          | 'Bushwick'          |           40.70339 | -73.92945 | 'Entire home/apt' |   130 |             30 |                53 | '30/06/17'  |              0.68 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 484297 | 'Large home in most desirable Brooklyn hood!' | 2397411 | 'John'    | 'Brooklyn'          | 'Clinton Hill'      |           40.68545 | -73.96534 | 'Entire home/apt' |   350 |              4 |                10 | '12/09/18'  |              0.12 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+---------------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [66]:
host_neighbourhood = etl.facet(data, ('host_name', 'neighbourhood_group'))

In [67]:
host_neighbourhood[('John', 'Brooklyn')]

+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id     | name                                          | host_id | host_name | neighbourhood_group | neighbourhood  | latitude           | longitude | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+========+===============================================+=========+===========+=====================+================+====================+===========+===================+=======+================+===================+=============+===================+================================+==================+
|   2539 | 'Clean & quiet apt home by the park'          |    2787 | 'John'    | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 | -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 400039 | 'Big Beautiful Railroad in Brooklyn'          | 1488809 | 'John'    | 'Brooklyn'          | 'Bushwick'     |           40.70339 | -73.92945 | 'Entire home/apt' |   130 |             30 |                53 | '30/06/17'  |              0.68 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 484297 | 'Large home in most desirable Brooklyn hood!' | 2397411 | 'John'    | 'Brooklyn'          | 'Clinton Hill' |           40.68545 | -73.96534 | 'Entire home/apt' |   350 |              4 |                10 | '12/09/18'  |              0.12 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 587641 | 'Luxury Pad NYC - Williamsburg Loft'          |  717562 | 'John'    | 'Brooklyn'          | 'Williamsburg' |            40.7197 | -73.95741 | 'Entire home/apt' |   275 |             30 |                 6 | '31/10/15'  |              0.07 |                              1 |              363 |
+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 841075 | 'Spacious and Clean Brooklyn Flat'            | 4392420 | 'John'    | 'Brooklyn'          | 'Bushwick'     |           40.70366 |  -73.9269 | 'Entire home/apt' |    85 |             15 |                22 | '22/10/16'  |              0.28 |                              1 |                0 |
+--------+-----------------------------------------------+---------+-----------+---------------------+----------------+--------------------+-----------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Return two tables, the first containing selected rows, the second containing remaining rows

In [68]:
affordable, expensive = etl.biselect(data, lambda rec: rec.price < 500)

In [69]:
affordable

+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id   | name                                               | host_id | host_name     | neighbourhood_group | neighbourhood  | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+======+====================================================+=========+===============+=====================+================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 2539 | 'Clean & quiet apt home by the park'               |    2787 | 'John'        | 'Brooklyn'          | 'Kensington'   | 40.647490000000005 |          -73.97237 | 'Private room'    |   149 |              1 |                 9 | '19/10/18'  |              0.21 |                              6 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 2595 | 'Skylit Midtown Castle'                            |    2845 | 'Jennifer'    | 'Manhattan'         | 'Midtown'      |           40.75362 | -73.98376999999999 | 'Entire home/apt' |   225 |              1 |                45 | '21/05/19'  |              0.38 |                              2 |              355 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3647 | 'THE VILLAGE OF HARLEM....NEW YORK !'              |    4632 | 'Elisabeth'   | 'Manhattan'         | 'Harlem'       | 40.809020000000004 |           -73.9419 | 'Private room'    |   150 |              3 |                 0 |         nan |               nan |                              1 |              365 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 3831 | 'Cozy Entire Floor of Brownstone'                  |    4869 | 'LisaRoxanne' | 'Brooklyn'          | 'Clinton Hill' | 40.685140000000004 |          -73.95976 | 'Entire home/apt' |    89 |              1 |               270 | '05/07/19'  |              4.64 |                              1 |              194 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 5022 | 'Entire Apt: Spacious Studio/Loft by central park' |    7192 | 'Laura'       | 'Manhattan'         | 'East Harlem'  |           40.79851 |          -73.94399 | 'Entire home/apt' |    80 |             10 |                 9 | '19/11/18'  |               0.1 |                              1 |                0 |
+------+----------------------------------------------------+---------+---------------+---------------------+----------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

In [70]:
expensive

+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| id    | name                                                | host_id | host_name  | neighbourhood_group | neighbourhood      | latitude           | longitude          | room_type         | price | minimum_nights | number_of_reviews | last_review | reviews_per_month | calculated_host_listings_count | availability_365 |
+=======+=====================================================+=========+============+=====================+====================+====================+====================+===================+=======+================+===================+=============+===================+================================+==================+
| 19601 | 'perfect for a family or small group'               |   74303 | 'Maggie'   | 'Brooklyn'          | 'Brooklyn Heights' |           40.69723 | -73.99268000000001 | 'Entire home/apt' |   800 |              1 |                25 | '04/08/16'  |              0.24 |                              1 |                7 |
+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 23686 | '2000 SF 3br 2bath West Village private  townhouse' |   93790 | 'Ann'      | 'Manhattan'         | 'West Village'     | 40.730959999999996 |          -74.00319 | 'Entire home/apt' |   500 |              4 |                46 | '18/05/19'  |              0.55 |                              2 |              243 |
+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 60164 | 'Beautiful, elegant 3 bed SOHO loft'                |  289653 | 'Harrison' | 'Manhattan'         | 'SoHo'             |           40.72003 |          -74.00262 | 'Entire home/apt' |   500 |              4 |                94 | '23/06/19'  |              0.99 |                              1 |              329 |
+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 61224 | 'Huge Chelsea Loft'                                 |  291112 | 'Frank'    | 'Manhattan'         | 'Chelsea'          |           40.74358 |          -74.00027 | 'Entire home/apt' |   500 |              2 |                35 | '27/07/17'  |              0.34 |                              1 |              348 |
+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
| 68974 | 'Unique spacious loft on the Bowery'                |  281229 | 'Alicia'   | 'Manhattan'         | 'Little Italy'     | 40.719429999999996 |          -73.99627 | 'Entire home/apt' |   575 |              2 |               191 | '20/06/19'  |              1.88 |                              1 |              298 |
+-------+-----------------------------------------------------+---------+------------+---------------------+--------------------+--------------------+--------------------+-------------------+-------+----------------+-------------------+-------------+-------------------+--------------------------------+------------------+
...

#### Using a context method
This filters out large upward changes in the FX rate. This is clearly a currency which swings quite wildly.

In [91]:
fx_rates = [['date', 'close'],
            ['2019-08-01', 10],
            ['2019-08-02', 15],
            ['2019-08-03', 13],
            ['2019-08-04', 10],
            ['2019-08-05', 17],
            ['2019-08-06', 20],
            ['2019-08-07', 21],
            ['2019-08-08', 20]]

In [92]:
def query(prv, cur, nxt):
     return ((prv is not None and (cur.close - prv.close) < 2)
     or (nxt is not None and (nxt.close - cur.close) < 2))

In [93]:
fx = etl.selectusingcontext(fx_rates, query)

In [94]:
fx.displayall()

date,close
2019-08-02,15
2019-08-03,13
2019-08-04,10
2019-08-06,20
2019-08-07,21
2019-08-08,20